//{name: "", id: "",  type:"", description:"", imgsrc: "", species: "", status: "", occupation: "", age: 0, nicknames: "", relationships: "", catchphrase: "", strengths: "", weaknesses: "", quotes: [{id: 0, text: ""}], totalDeaths: , deaths: [{id: 0, text: ""}], fact: "" , actor:"", funfacts: [{id: 1, text: ""}]}
export let characters= [
    //DEAN WINCHESTER
    {name: "Dean Winchester", id: "dean", type:"human", description:"The older Winchester brother, raised as a hunter by his dad after their mom was killed by a demon. Dean is fiercely protective of Sam and takes on the big-brother, soldier role. He's driven by loyalty, family, and a deep sense of responsibility—even when it eats him up inside.", 
    imgsrc: "/assets/characters/dean.gif",
    species:"Human", status: "Dead",occupation: "Hunter", age: 39, nicknames: "Squirrel/Not Moose (Crowley), Deano (Gabriel)", relationships: "John (Father), Sam (Brother), Mary (Mother), Adam (Half-Brother)", catchphrase: "", strengths: "Monster Hunting, Sarcasm, Self-Loathing", weaknesses: "Pie, Family, Healthy Relationships, Communication",
    quotes: [
        { id: 1, text: "Driver picks the music, shotgun shuts his cakehole." },
        { id: 2, text: "I don't have a plan, but what I do have is a GED and a give 'em hell attitude" },
        {id: 3, text: "Dad's on a Hunting Trip and he hasn't been home in a few days."}
    ],          
    totalDeaths: 100,
    deaths: [
        { id: 1, text: "Suffocation" },
        { id: 2, text: "Electrocution" },
        { id: 3, text: "Hit by a Car" },
        { id: 4, text: "Heart Attack" },
        { id: 5, text: "Attacked by Hell-Hounds" },
        { id: 6, text: "Shot" },
        { id: 7, text: "Impaled" },
        { id: 8, text: "Drug Overdoses (Suicide Attempt)" }
    ],          
    funfacts:[{id:1, text: "Dean died over 100 times in Mystery Spot Alone!"}], actor: "Jensen Ackles"},
    //SAM WINCHESTER
    {name: "Sam Winchester", id: "sam",  type:"human", description:"The younger Winchester, more thoughtful and academic. He tried to escape hunting by going to college, but got pulled back in after Dean came to him with news about their missing father. Sam often questions the morality of hunting, but is just as committed to saving people.",
        imgsrc: "/assets/characters/sam.gif",
        species:"Human", status: "Dead", occupation: "Hunter", age: 70, nicknames: "Bitch/Sammy (Dean), Moose/ Jolly Green/Samantha (Crowley)", relationships: "Dean (Brother), John (Father), Mary(Mother), Adam (Half-Brother)", catchphrase: "According to the Lore, So Get This...", strengths: "Intelligence, Empathy, Communication", weaknesses: "Demon Blood, Dean, Clowns", 
        quotes: [{id:1, text: "I've been tortured by the devil himself, what can you do to me?"}, {id:2, text:"If there is a key, then there must also be a lock"}, {id: 3, text:"Yesterday was Tuesday, but today is Tuesday too!"}], 
        totalDeaths: 8, 
        deaths: [{id: 1, text: "Stabbed"}, {id:2, text:"Shot"}, {id:3, text:"Witchcraft"}, {id:4, text:"Natural Causes"}, {id:5, text:"Struck by Lightning"}, {id:6, text:"Attacked by Vampires"}], actor:"Jared Padalecki", funfacts: [{id:1, text:"He is the only character to appear in every episode of the series."}, {id:2, text:"He is the only Winchester to not have successfully made a deal with a demon."}]
    },
    //BOBBY SINGER
    {name: "Robert \"Bobby\" Singer", id: "bobby", type:"human", description:"A father figure to Sam and Dean, Bobby is an experienced, no-nonsense hunter who helps guide and support them. He’s deeply knowledgeable about lore and demon-hunting, and treats the brothers like his own kids.",
        imgsrc: "/assets/characters/bobby.gif", 
        species:"Human", status: "Dead", occupation: "Hunter", age: 64, nicknames: "", relationships: "Karen (wife), Dean (adopted son), Sam (adopted son)", catchphrase: "Idgits, Balls", strengths: "Intelligent, Resourceful, Networking/Personal Connections", weaknesses: "Paranoia, Sam and Dean Winchester", quotes: [{id: 1, text: "As fate would have it, I adopted two boys and they grew up great. They grew up heroes!"}, {id: 2, text: "Get the hell of my property before I blast you so full of rocksalt you're gonna crap margaritas."}, {id:3, text:"Family don't end with bloody, boy."}], totalDeaths: 4, deaths: [{id: 1, text: "Killed by Lucifer"}, {id: 2, text: "Shot by Dick Roman"}], fact: "His character was created because Missouri Mosely's actress got an offer for Grey's Anatomy and could not stay for Supernatural." , actor:"Jim Beaver", funfacts: [{id:1, text:"An alternate version of Bobby, from Apocalypse world, lives on the original earth."}]
    },
    //JODY MILLS
    {name: "Jody Mills", id: "jody", type:"human", description:"A sheriff who becomes an ally after a supernatural case in her town. After losing her family, she becomes a hunter and ends up fostering wayward teens like Claire and Alex. She helps build a network of female hunters.", imgsrc: "/assets/characters/jody.gif", species:"Human", status: "Alive", occupation: "Sheriff, Hunter", age: 41, nicknames: "", relationships: "Sean (husband), Owen (Son), Claire Novak (adopted daughter), Alex (adopted daughter)", catchphrase: "", strengths: "Brave, Skilled with firearms, Compassionate", weaknesses: "Her Girls, The Winchester Boys", quotes: [{id: 1, text: "No, Sam. She smokes grass under the bleachers, but at least she's not luring men to their deaths."}, {id: 2, text: "It's not enough that you kill people. You've got to rob them, too? And to think, I gave you lunch money."}], totalDeaths: 0, deaths: [], actor: "Kim Rhodes", funfacts:[{id:1, text:"Dean throws in a funny nod to The Suite Life of Zack & Cody — the Disney show Kim Rhodes is known for — by telling Zachariah, \"It's the Suite Life of Zach and Cass.\""}]},

    //CLAIRE NOVAK
    {name: "Claire Novak", id: "claire", type:"human",description:"The daughter of Jimmy Novak, Castiel’s vessel. Claire struggles with abandonment and anger but eventually finds her place as a capable hunter. She sees Jody as a mother figure and slowly opens up to the idea of found family.", imgsrc: "/assets/characters/claire.gif", species:"Human", status: "Alive", occupation: "Hunter", age: 20, nicknames: "Biker Barbie (Alex)", relationships: "Jody Mills (Guardian), Castiel (Guardian), Jimmy (Father), Amelia (Mother)", catchphrase:"", strengths: "Determined, Strong", weaknesses: "Inexperience, Emotional vulnerability", quotes: [{id: 1, text: "I kill monsters. That's who the hell I am."}, {id: 2, text: "Ketchup is a vegetable."}], totalDeaths: 0, deaths: [], actor: "Kathryn Newton", funfacts:[{id:1, text:"Her father is Castiel's main vessel, but she was his vessel temporarily as a child."},{id:2, text:"Castiel gets his signature tie because Claire tells him he would look better in a tie"},{id:3, text:"Claire was the only werewolf to have ever been cured."}]},

    //ADAM MILLIGAN
    {name:"Adam Milligan",id:"adam",type:"human",description:"Sam and Dean’s half-brother, born to John Winchester and another woman. He becomes Michael’s vessel and is eventually trapped in the Cage with Lucifer for years. His arc reflects the consequences of John’s choices.", imgsrc:"/assets/characters/adam.gif",species:"Human",status:"Alive",occupation:"Human Vessel",age:"35",nicknames:"",relationships:"John (Father), Kate(Mother), Sam and Dean (half-brothers)",catchphrase:"I just want a normal life.",strengths:"Resilience, strong moral compass",weaknesses:"Lack of combat training, human vulnerability",quotes:[{id:1,text:"Guess we all have Daddy issues, huh?"},{id:2,text:"Since when do we get what we deserve?"}, {id:3, text:"You and that toilet have something in common. You are both full of crap. Practically overflowing, Dean."}],totalDeaths:1,deaths:[{id:1, text:"Killed by a Ghoul"}],actor:"Jake Abel", funfacts: [{id:1, text:"Adam is brought back by Zachariah to be the vessel for Michael after Dean refuses. He later develops a close relationship with Michael after being locked in the Cage together."}]},
    
    //JOHN WINCHESTER
    {name:"John Winchester",id:"john",type:"human",description:"Sam and Dean’s father. After Mary’s death, he became obsessed with revenge and turned his sons into hunters. His legacy is both a burden and a blueprint for the boys.", imgsrc:"/assets/characters/john.gif",species:"Human",status:"Dead",occupation:"Hunter, (Former) Mechanic, (Former) Marine",age:"52",nicknames:"",relationships:"Henry (Father), Mary (wife), Samuel (father-in-law), Deanna (mother-in-law) Sam and Dean/Adam (sons)",catchphrase:"",strengths:"Expert hunter, tactical skills, determination",weaknesses:"Obsessiveness, His Boys",quotes:[{id:1,text:"You take care of each other. I am so proud of you boys."},{id:2,text:"If something tries busting in? Shoot first, ask questions later"}, {id:3, text:"Lock the doors and windows, close the shades, and most important...watch out for Sammy."}],totalDeaths:2,deaths:[{id:1, text:"Neck snapped by Azazel"},{id:2,text:"Made a demon deal with Azazel to save Dean."}],actor:"Jeffrey Dean Morgan", funfacts:[{id:1, text:"While he raised Sam and Dean as hunters, he raised Adam to have a normal life."}]},
    
    //MARY WINCHESTER
    {name:"Mary Winchester",id:"mary",type:"human",description:"Sam and Dean’s mom. Once a hunter herself, she was killed by Azazel, which launched the whole Winchester journey. Later resurrected, she struggles to connect with her adult sons and reconcile her past with their present.", imgsrc:"/assets/characters/mary.gif",species:"Human",status:"Dead",occupation:"Hunter, Woman of Letters, Resistence Leader",age:"40s",nicknames:"",relationships:"Samuel (Father), Deanna (Mother) Henry (father-in-law), John (husband), Sam and Dean(sons)",catchphrase:"",strengths:"Skilled hunter, resilience, maternal instincts",weaknesses:"Her Boys",quotes:[{id:1,text:"You know the worst thing I can think of, the very worst thing? Is for my children to be raised into this like I was."},{id:2,text:"Angels are watching over you."}, {id:3, text:"Get away from my boys."}],totalDeaths:1,deaths:[{id:1,text:"Killed in a fire by Azazel"}, {id:2, text:"Vaporized by Jack"}],actor:"Samantha Smith", funfacts: [{id:1, text:"Amara brought her back as a thank you to Dean for helping her fix her relationship with God."}, {id:2, text:"She would sing \"Hey Jude\" as a lullaby for Dean."}]},
    
    //HENRY
    {name:"Henry Winchester",id:"henry",type:"human", description:"John’s father and a member of the Men of Letters. He accidentally time-travels to meet his grandsons. He represents a more academic, magical side of the family—one that John never knew.",imgsrc:"/assets/characters/henry.gif",species:"Human",status:"Dead",occupation:"A Men of Letters",age:"Unknown",nicknames:"",relationships:"Millie (wife), John (son), Mary (daughter-in-law), Sam and Dean/Adam (grandsons)",catchphrase:"",strengths:"Research skills, hunting expertise",weaknesses:"Family",quotes:[{id:1,text:"There's a price we pay for upholding great responsibility"}, {id:2, text:"I didn't know my son as a man, but having met you two, I know I would have been proud of him."}, {id:3, text:"You're also Winchesters. As long as we're alive, there is always hope."}],totalDeaths:1,deaths:[{id:1,text:"Killed by Abaddon"}],actor:"Gill McKinney", funfacts:[{id:1,text:"He travels to the future in an attempt to keep a key safe from Abaddon, but ultimately ends up meeting his death before he can return."}]},
    
    //SAMUEL
    {name:"Samuel Campbell",id:"samuel",type:"human", description:"Mary’s father and Sam and Dean’s maternal grandfather. A seasoned hunter who’s brought back by Crowley and plays a morally ambiguous role. His loyalty to family sometimes blinds him.",imgsrc:"/assets/characters/samuel.gif",species:"Human",status:"Dead",occupation:"Hunter",age:"Deceased",nicknames:"",relationships:"Jebediah (Grandpa), Deanna (wife), Mary (daughter), John (son-in-law), Dean and Sam (grandsons)",catchphrase:"",strengths:"Hunting skills, leadership",weaknesses:"Pride, Highly succeptible to possession",quotes:[{id:1,text:"Don't think there's going to be a next time."},{id:2,text:"I don't trust other hunters, Dean. Don't want their help. Don't want them around my family."}, {id:3, text:"You think there were maybe calmer ways we could have done all that?"}, {id:4, text:"Tell me, what exactly are you supposed to be to me?"}],totalDeaths:2,deaths:[{id:1,text:"Stabbed himself in the stomach because he was possessed by Azazel"}, {id:2, text:"Head shot by Sam because he was possessed by a Khan worm"}], actor:"Mitch Pileggi"},
    
    //CHARLIE
    {name:"Charlie Bradbury",id:"charlie",type:"human", description:"A quirky, nerdy hacker turned hunter who first helps the Winchesters with tech stuff, then becomes a close friend. She's brave, clever, and resourceful, and helps bring heart and humor to the darker moments.",imgsrc:"/assets/characters/charlie.gif",species:"Human",status:"Dead",occupation:"Hacker/ Hunter, (Former) IT employee",age:"28",nicknames:"Celeste Middleton, Queen of Moons",relationships:"Gertrude Middleton (Mother)",catchphrase:"",strengths:"Tech skills, hacking, bravery",weaknesses:"Physical combat, emotional vulnerability",quotes:[{id:1,text:"You hit like a girl who never learned how to hit!"},{id:2,text:"I was drunk! It was Comic-Con!"}, {id:3, text:"I'm going to die. I should have taken that job at Google."}],totalDeaths:2,deaths:[{id:1, text:"Killed by the Wicked Witch"}, {id:2, text:"Murdered in a hotel bathtub by Frankenstein"}],actor:"Felicia Day", funfacts: [{id:1, text:"The Winchesters come across an alternate version of Charlie in Apocalypse World"}, {id:2, text:"She once dated Dorothy and lived in the land of Oz."}]},
    
    //JO HARVELLE
    {name:"Jo Harvelle",id:"jo",type:"human", description:"The daughter of hunters Ellen and Bill Harvelle. She wants to prove herself as a serious hunter but often clashes with Dean, who sees her as someone to protect. Her relationship with the Winchesters grows more mature over time.",imgsrc:"/assets/characters/jo.gif",species:"Human/Ghost",status:"Dead",occupation:"Hunter, Bartender/Barback at Harvelle's Roadhouse",age:"Young Adult",nicknames:"",relationships:"Ellen (mother)",catchphrase:"",strengths:"Marksmanship, combat skills",weaknesses:"Emotional vulnerability",quotes:[{id:1,text:"You carry all kinds of crap you don't have to, Dean. It kinda gets clearer when you're dead."}, {id:2, text:"This is why we're here, right? If I could get us a shot on the Devil, Dean, we have to take it."}],totalDeaths:1,deaths:[{id:1,text:"Killed from explosion with Ellen, major injuries from Hellhounds"}],actor:"Alona Tal", funfacts:[{id:1, text:"Jo was forced against her will by Osiris to kill Dean, but Sam ultimately frees her from Osiris's control "}, {id:2, text:"While John wrote in a journal, Jo logged her life experiences on an online blog."}]},

    //ASH 
    {name:"Ash",id:"ash",type:"human", description:"A brilliant, eccentric tech expert who lives at the Roadhouse. He uses his hacking and research skills to help hunters find cases and track supernatural activity.",imgsrc:"/assets/characters/ash.gif",species:"Human",status:"Dead",occupation:"Hacker, Employee at Harvelle's Roadhouse",age:"Unknown",nicknames:"",relationships:"Ellen and Jo Harvelle (coworkers)",catchphrase:"I bring chaos with a grin.",strengths:"Intelligence, Computer Skills",weaknesses:"His Humanity",quotes:[{id:1,text:"All business up front, party in the back."}, {id:2, text:"You boys die more than anyone I've ever met."}, {id:3, text:"You ever been struck by lightning? It ain't fun."}],totalDeaths:1,deaths:[{id:1,text:"Killed in destruction of Harvelle's Roadhouse"}],actor:"Chad Lindberg", funfacts:[{id:1, text:"He attended MIT, but was kicked out for fighting."}, {id:2, text:"When he greets Sam and Dean in Heaven, he is dressed as a Mexican lucha libre fighter."}]},
    
    //ELLEN HARVELLE
    {name:"Ellen Harvelle",id:"ellen",type:"human", description:"Jo’s protective mom and a seasoned hunter. She runs the Harvelle Roadhouse, a hub for hunters. She’s strong-willed and fiercely loyal to her family and the Winchesters.",imgsrc:"/assets/characters/ellen.gif",species:"Human",status:"Dead",occupation:"Hunter/Bar Owner",age:"55",nicknames:"",relationships:"Jo (daughter), William (husband)",catchphrase:"We fight to protect what matters.",strengths:"Hunting knowledge, leadership",weaknesses:"Physical vulnerability, maternal instincts",quotes:[{id:1,text:"Family is everything."}, {id:2, text:"Yeah, and Hannibal Lecter is a good psychiatrist..."}, {id:3, text:"You smell like a bar, you know that?"}, {id:4, text:"Everybody get in here! it's time for the lineup. Usual suspects in the corner."}],totalDeaths:1,deaths:[{id:1,text:"Killed in an explosion with Jo"}],actor:"Samantha Ferris", funfacts:[{id:1, text:"Ellen is an acquaintance of John Winchester"}, {id:2, text:"In a timeline where the Titanic doesn't sink, Ellen is married to Bobby Singer."}]},
    
    //RUFUS TURNER
    { name: "Rufus Turner", id: "rufus", type:"human",description:"Bobby’s grumpy, sarcastic old hunting partner. Rufus is rough around the edges but dependable when it counts. He and Bobby have a love-hate friendship full of banter.", imgsrc: "/assets/characters/rufus.gif", species: "Human", status: "Dead", occupation: "Hunter", age: "Older Adult", nicknames: "Luther Vandross, Ruben Studdard", relationships: "Bobby (Best Friend)", catchphrase: "", strengths: "Research, experience, hunting skills", weaknesses: "Physical vulnerability", quotes: [ { id: 1, text: "Even if we find a way to keep the world spinnin', not everyone's gonna be on that bus ride home. Sacrifice, the greater good, all that jazz... oldest rule in hunting, Bobby. You can't save everyone." }, {id:2, text:"It's officially none of your damn business, ma'am."}, {id:3, text:"This can't be my afterlife cuz the three of you are here."} ], totalDeaths: 1, deaths: [ { id: 1, text: "Killed by a monster" } ], actor: "Steven Williams", funfacts: [{id:1, text:"Rufus is Jewish and would try to get out of burying bodies if it was Sabbath."}] },

    //LISA BRAEDEN
    {name:"Lisa Braeden",id:"lisa",type:"human", description:"Dean’s ex-girlfriend and the mother of Ben, a boy Dean thinks might be his son. Lisa represents the normal life Dean wishes he could have, and she gives him a glimpse of peace—however temporary.",imgsrc:"/assets/characters/lisa.gif",species:"Human",status:"Alive",occupation:"Yoga Instructor",age:"Adult",nicknames:"",relationships:"Ben (son), Dean (ex-boyfriend)",catchphrase:"",strengths:"Supportive, resilient",weaknesses:"No knowledge of the Supernatural",quotes:[{id:1,text:"Dean, you don't have to do this alone."}, {id:2, text:"But I didn't expect Sam to come back. And I'm glad he's okay. I am. But the minute he walked through that door, I knew it was over."}], totalDeaths:0, deaths:[], actor:"Cindy Sampson", funfacts:[{id:1, text:"She told her friends that her one night stand with Dean was the \"best night of her life\""}, {id:2, text:"After facing danger from Crowley, Dean has Castiel erase all her memories of him and the supernatural to protect her."}]},

    //MICK DAVIES
    {name:"Mick Davies",id:"mick",type:"human", description:"A high-ranking British Men of Letters operative who tries to bring order to American hunting. He starts out arrogant but softens as he spends more time with Sam and Dean. Ultimately, he questions the organization’s harsh methods.",imgsrc:"/assets/characters/mick.gif",species:"Human",status:"Dead",occupation:"British Men of Letters",age:"40s",nicknames:"Dr. Buckingham/Harry Potter (Dean), Frodo (Sam)",relationships:"Winchesters (adversaries)",catchphrase:"",strengths:"Tactical, resourceful, combat skills",weaknesses:"Rigid loyalty, moral ambiguity",quotes:[{id:1,text:"The code is what makes a young boy kill his best friend. But I'm a man now, Dr. Hess, and I can see the choices. And I choose to do the right thing."}],totalDeaths:1,deaths:[{id:1, text:"Shot execution style by Arthur Ketch (on orders)"}],actor:"Adam Fergus", funfacts:[{id:1, text:"When he was a child, he was forced to murder his best friend by Dr. Hess."}, {id:2, text:"Mick is the first British Men of Letters operative to switch sides and support the hunters."}, {id:3, text:"Dr. Hess is the only one to call him Michael. Everyone else calls him Mick."}]},
    
    //ARTHUR KETCH
    {name:"Arthur Ketch",id:"ketch",type:"human", description:"A ruthless assassin for the British Men of Letters. Initially an antagonist, he eventually allies with the Winchesters—though his loyalty is always suspect. He's cold, but complicated.",imgsrc:"/assets/characters/ketch.gif", species:"Human", status:"Dead", occupation:"Mercenary, (Former) British Men of Letters",age:"45",nicknames:"Low-rent Christian Bale/ Dick-bag (Dean)",relationships:"Mick Davies (boss), Asmodeus (former boss) ",catchphrase:"",strengths:"Skilled hunter, loyal, resourceful, high pain tolerance", weaknesses:"Conflicted loyalties",quotes:[{id:1,text:"We do what needs to be done."}, {id:1, text:"We don't need a conscience. Such a trite idea, but we firmly believe the ends do justify the means"}],"totalDeaths":2,"deaths":[{id:1, text:"Shot in the head by Mary"}, {id:2, text:"Heart ripped out by Ardat"}],"actor":"David Haydn-Jones", funfacts:[{id:1, text:"He had Rowena implant a Resurrection Seal inside him"}, {id:2, text:"He did have a romantic relationship with Mary Winchester"}]},

    //EILEEN LEAHY
    {name: "Eileen Leahy", id: "eileen", type:"human",description:"", imgsrc: "/assets/characters/eileen.gif", species: "Human/Ghost", status: "Alive", occupation: "Hunter", age: 35, nicknames: "", relationships: "Padraic (Father), Maura (Mother)", catchphrase: "Keep your eyes open.", strengths: "Tracking, Combat skills, Spell Casting", weaknesses: "Trust issues", quotes: [{id: 1, text: "You never know what’s out there."}], totalDeaths: 2, deaths: [{id:1, text:"Murdered by a hellhound"}, {id:2, text:"Existence erased by God."}], actor: "Shoshannah Stern", funfacts:[{id:1, text:"Eileen lost her parents and her hearing after being attacked by a Banshee as a child."}, {id:2, text:"She is a legacy member to the Men of Letters."}, {id:3, text:"She often uses ASL when communicating with Sam, but can read lips and speak coherently."}, {id:4, text:"She is the first deaf hunter to be introduced in the series"}]},

    //ROWENA MACLEOD
    {name: "Rowena MacLeod", id: "rowena", type:"human", description:"A powerful Scottish witch and Crowley’s mother. She starts out as a villain but becomes a reluctant ally. Ambitious, sharp, and fabulous, she slowly reveals a more caring side—especially toward Sam.",imgsrc: "/assets/characters/rowena.gif", species: "Human/Witch", status: "Deceased", occupation: "", age: "Centuries old", nicknames: "The Queen of Hell, Red", relationships: "Crowley (son)", catchphrase: "", strengths: "Powerful magic, Cunning, Knowledge of spells", weaknesses: "Pride, Family issues", quotes: [{id: 1, text: "I am a flawed, petty, evil creature, Samuel, and I don't know if I can be redeemed. but I have to try."}, {id: 2, text: "Hardly the most appetizing process in the world, but killing demons always makes me hungry."}, {id:3, text:"You say that like it's an insult. Nice girls, they're pathetic. Here's to evil skanks!"}], totalDeaths: 3, deaths: [{id:1, text:"Neck snapped by Lucifer"}, {id:2, text:"Head crushed and body burned by Lucifer"},{id: 3, text: "Killed by Sam for a magical spell"}], actor: "Ruth Connell", funfacts: [{id:1, text:"Sam creates witch-killing bullets to kill Rowena, but she ends up using them to save her life."}]},

    //MONSTERS-----------------------------------------
    // BENNY LAFEYETTE
    { name: "Benny Lafeyette", id: "benny",type:"monster", description:"A vampire with a human soul who helped Dean escape Purgatory. Dean trusts him deeply, even though his nature makes him a controversial ally. Benny shows that not all monsters are evil.", imgsrc: "/assets/characters/benny.gif", species: "Vampire", status: "Dead", occupation: "Vampirate, Employee at Guidry's Cajun Cafe", age: "Unknown", nicknames: "", relationships: "Elizabeth (great-granddaughter)", catchphrase: "You don't have to trust me, just don’t kill me.", strengths: "Superhuman strength, Loyalty, Combat skills", weaknesses: "Sunlight, Holy water", quotes: [{ id: 1, text: "I'm not the bad guy." }, { id: 2, text: "Sometimes the enemy of my enemy is my friend." }, {id:3, text: "What I loved, it ain't here anymore. It was snuffed out long ago by monsters like me."}], totalDeaths: 2, deaths: [{id:1, text:"Beheaded by Dean (consentual)"}, {id:2, text:"Killed in Purgatory"}], actor: "Ty Olsson", funfacts: [{id:1, text:"He was turned by an ancient vampire known as \"The Old Man\""}, {id:2, text:"He makes a deal with Dean in order to escape purgatory, but later agrees to go back to save Sam"}] },

    //GARTH FITZGERALD
    { name: "Garth Fitzgerald IV", id: "garth",type:"monster", description:"A goofy, lovable hunter-turned-werewolf. He starts as comic relief but proves himself smart, loyal, and kind. He eventually builds a peaceful life with a werewolf pack and still helps out the Winchesters.", imgsrc: "/assets/characters/garth.gif", species: "Werewolf", status: "Alive", occupation: "Hunter, Dentist", age: 40, nicknames: "", relationships: "Bess (Wife), Gertie (daughter), Sam (son), Castiel (son)", catchphrase: "You've been 'Garth-ed'!", strengths: "Loyal, Knowledgeable, Kind", weaknesses: "Silver, His Family", quotes: [{ id: 1, text: "It messes with my depth perception- especially when I skinny dip." }, { id: 2, text: "Why do people keep thinking I'm threatening them?" }], totalDeaths: 0, deaths: [], actor: "DJ Qualls", funfacts:[{id:1, text:"Garth's first kill as a hunter was the Tooth Fairy"}, {id:2, text:"After Bobby dies, Garth takes over his role- assigning cases and providing assistance to other hunters."}, {id:3, text:"His sock puppet's name is Mr. Fizzles."}] },

    //DEMONS --------------------------------------------------
    // CROWLEY
    {name: "Crowley", id: "crowley",type:"demon", description:"The King of Hell. A clever, sarcastic demon who often works with the Winchesters when it suits his goals. Despite his villainy, he becomes oddly sympathetic over time—especially in his strained relationship with his mother, Rowena.", imgsrc: "/assets/characters/crowley.gif", species: "Demon", status: "Deceased", occupation: "King of Hell, (Former) King of Crossroads", age: "356", nicknames: "", relationships: "Rowena (Mother), Gavin (Son)", catchphrase: "Hello, Boys", strengths: "Powerful demon, Manipulation, Deal making", weaknesses: "Trust issues, Loyalty conflicts", quotes: [{id: 1, text: "I'm a lover, not a fighter."}, {id: 2, text: "You're only as strong as the company you keep."}, {id: 2, text: "You don't know what it's like to be HUMAN!"}], totalDeaths: 1, deaths: [{id: 1, text: "Sacraficed himself for the Winchester Boys"}], actor: "Mark Sheppard", funfacts:[{id:1, text:"His true form's color is a dark red, as opposed to the traditional black of other demons"}, {id:2, text:"His phone number is 666 and his ringtone is Baby Got Back by Sir Mix-a-lot."}]},

    //LILITH
    { name: "Lilith", id: "lilith", type:"demon", description:"A powerful white-eyed demon and the first demon ever created. She breaks the 66 seals to free Lucifer. Her death is the final seal. She’s one of the major villains of the earlier seasons.",imgsrc: "/assets/characters/lilith.gif", species: "Demon", status: "Dead", occupation: "", age: "Ancient", nicknames: "The First Demon, Queen of Demons", relationships: "Lucifer (Master), Meg (follower)", catchphrase: "I am the beginning and the end.", strengths: "Possession, soul manipulation, necromancy", weaknesses: "Exorcism, demon-killing knives, holy water, angel blade", quotes: [{ id: 1, text: "The cage was never meant to hold me." }, { id: 2, text: "You'll all burn in hell." }, {id:3, text:"You killed me because I let you. Now I'm feeling... less generous"}], totalDeaths: 1, deaths: [{ id: 1, text: "Killed by Sam Winchester with demon-killing knife" }], actor: "Katherine Boecher", funfacts:[{id:1, text:"She is responsible for breaking the first seal of the Apocalypse."}, {id:2, text:"She is the first demon to be brought back to life in the series."}]},

    //MEG MASTERS
    { name: "Meg Masters", id: "meg", type:"demon", description:"A demon who serves various masters over time but ends up helping the Winchesters and falling for Castiel. She’s snarky, dangerous, but surprisingly brave in the end.",imgsrc: "/assets/characters/meg.gif", species: "Demon", status: "Dead", occupation: "Hunter, (Former) Nurse", age: "Unknown", nicknames: "", relationships: "Crowley (ally), Lucifer (master)", catchphrase: "", strengths: "Demonic powers, possession, cunning", weaknesses: "Exorcism, holy water, demon weapons, angel blade", quotes: [{ id: 1, text: "Wait, that's how you spent your last year? With a chick? LAME." }, { id: 2, text: "Keep talking dirty, makes my meat-suit all dewy." }, {id:3, text:"Hi. I'm Meg. I'm a demon."}], totalDeaths: 1, deaths: [{id:1, text:"Killey by Crowley"}], actor: "Rachel Miner", funfacts: [{id:1, text:"Meg was the first demon to kill an angel on the screen"}, {id:2, text:"Meg is the first demon to be trapped in a Devils trap by Sam and Dean."}] },

    //RUBY
    { name: "Ruby", id: "ruby",type:"demon", description:"A demon who manipulates Sam by pretending to help him. She trains him to use his powers and tricks him into freeing Lucifer. Her betrayal hits hard.", imgsrc: "/assets/characters/ruby.gif", species: "Demon", status: "Dead", occupation: "(Former) Witch", age: "Unknown", nicknames: "", relationships: "Sam Winchester (relationship)", catchphrase: "", strengths: "Possession, demon magic, manipulation", weaknesses: "Exorcism, demon weapons, angel blade", quotes: [{ id: 1, text: "Come on, Sam! Even you have to admit- I'm awesome!" }, {id:2, text:"You didn't need the feather to fly, you had it in you the whole time, Dumbo."},{ id: 3, text: "Angels? They smite first and ask questions later." }], totalDeaths: 1, deaths: [{ id: 1, text: "Stabbed with demon-killing knife by Dean" }], actor: "Genevieve Cortese", funfacts: [{id:1, text:"Ruby helps Sam develop and strengthen his powers to get him strong enough to break the last seal and start the Apocalypse."}] },

    //CAIN
    { name: "Cain", id: "cain", type:"demon", description:"The original Knight of Hell. Once a legendary killer, he gave up violence for love. Dean seeks him out for the Mark of Cain. Cain is a dark mirror for Dean—showing where the Mark can lead.",imgsrc: "/assets/characters/cain.gif", species: "Knight of Hell", status: "Dead", occupation: "", age: "Ancient", nicknames: "The Father of Murder (Crowley)", relationships: "Colette (Wife), Dean Winchester (successor)", catchphrase: "I'm the one who broke the first mark.", strengths: "Mark of Cain, superhuman strength, combat", weaknesses: "The Mark's curse, divine weapons", quotes: [{ id: 1, text: "The mark can be transferred to someone who is worthy." }, { id: 2, text: "You have to know that with the Mark comes a great burden." }], totalDeaths: 1, deaths: [{ id: 1, text: "Killed by Dean Winchester" }], actor: "Timothy Osmund", funfacts:[{id:1, text:"He was responsible for training the Knights of Hell and hand picked the demonic order himself."}, {id:2, text:"He says he killed Abel because he didn't want Lucifer to corrupt him."}] },

    //ANGELS AND CELESTIALS --------------------------------------------------------
    //CASTIEL
    {name: "Castiel", id: "castiel",type:"angel", description:"An angel who first appears when he pulls Dean out of Hell. At first emotionless and obedient, Cas becomes one of the brothers' closest friends, questioning Heaven's orders and often rebelling for the sake of humanity.",
        imgsrc: "/assets/characters/castiel.gif",
        species: "Angel", status: "Dead", occupation: "", age: "Ancient", nicknames: "Cas (Dean), Clarence (Meg), Feathers (Crowley)", relationships: "God (Father), Angels (Siblings), Jack Kline (nephew)", catchphrase: "Hey, Assbutt.", strengths: "Strength, Healing, Loyalty", weaknesses: "The Winchester Brothers", 
        quotes: [{id: 1, text: "I'm the one who gripped you tight and raised you from perdition."}, {id: 2, text: "I'm hunted. I rebelled. I did all of it, for you."}, {id:3, text:"This isn't funny, Dean. The voice says I'm almost out of minutes."}], 
        totalDeaths: 6, 
        deaths: [{id: 1, text: "exploded"},{id: 2, text: "overconsumption of leviathan souls"},{id: 3, text: "Stabbed by an angel blade (x2)"},{id: 4, text: "Deal with the Shadow"}], fact: "The character's name was chosen because Supernatural runs on Thursdays.", actor: "Misha Collins"
    },
    // GABRIEL
     {name: "Gabriel", id: "gabriel", type:"angel", description:"An archangel who hides as the trickster “Loki.” He’s sarcastic and fun-loving but ultimately wants to avoid the apocalypse. He eventually joins the fight against his family.",imgsrc: "/assets/characters/gabriel.gif", species: "Archangel", status: "Deceased", occupation: "", age: "Ancient", nicknames: "The Trickster, Loki, Gabe", relationships: "God (Father), Michael (Brother), Lucifer (Brother), Angels (Siblings)", catchphrase: "Life's a joke, and I'm the punchline.", strengths: "Reality manipulation, Illusions", weaknesses: "Family conflict, Holy Oil, Supernatural Handcuffs, Archangel Blade", quotes: [{id: 1, text: "Lucifer, you're my brother. And I love you. But you are a great big bag of dicks."}, {id: 2, text: "All I did on Earth was run. I'm not running anymore."}], totalDeaths: 1, deaths: [{id: 1, text: "Killed by Lucifer"}], actor: "Richard Speight Jr.", funfacts:[{id:1, text:" He was the first celestial being on the show, but the last archangel to be revealed to viewers."}, {id:2, text:"His wings are blue"}]},
    
    //LUCIFER
    { name: "Lucifer", id: "lucifer",type:"angel", description:"The fallen archangel and ultimate antagonist for much of the series. Charismatic, cruel, and manipulative, Lucifer is obsessed with proving he’s right about humanity’s flaws.",imgsrc: "/assets/characters/lucifer.gif", species: "Archangel", status: "Dead", occupation: "", age: "Ancient", nicknames: "The Devil, Satan, Samael, Morning Star, Luci, Dark Prince, Lu, The Dark Angel", relationships: "God (Father), Michael (brother), Gabriel (brother), Angels (Siblings), Jack (Son)", catchphrase: "", strengths: "Immense power, manipulation, immortality", weaknesses: "Jack, Michael", quotes: [{ id: 1, text: "All those times you ran away, you weren't running from them: you were running towards me." }, { id: 2, text: "Snapping necks and cashing checks is what I do." }, { id: 1, text: "Hail to the King, baby!" }], totalDeaths: 2, deaths: [{ id: 1, text: "Stabbed with Archangel Blade by Dean" }, { id: 2, text: "Stabbed with Archangel Blade by Michael" }], actor: "Mark Pellegrino" , funfacts:[{id:1, text:"He is the first fallen angel and the creator of demons"}, {id:2, text:"He is the only archangel to have a special eye color- red"}]},

    
    //METATRON
    { name: "Metatron", id: "metatron",type:"angel", description:"God’s former scribe. He becomes power-hungry and tries to take over Heaven. Later, he redeems himself a bit by helping the Winchesters—though his actions cost many lives.",imgsrc: "/assets/characters/metatron.gif", species: "Angel", status: "Dead", occupation: "Scribe of God, (Former) Ruler of Heaven", age: "Ancient", nicknames: "The Scribe, Marv, X ", relationships: "God (Father), Angels (Siblings)", catchphrase: "", strengths: "Writing, Pop Culture Knowledge, Devising Plans/Deception", weaknesses: "Pride, ambition, Holy Oil, Supernatural Handcuffs, Angel Blade", quotes: [{ id: 1, text: "I know I'm a disappointment, but you are wrong about humanity." }, { id: 2, text: "What writer doesn't love a good twist?" }, {id:3, text:"Do you have any idea how much pancake makeup and soft lighting it took to get God to work a rope-line? He hated it."}], totalDeaths: 1, deaths: [{id:1,text:"Imploded by Amara"}], actor: "Curtis Armstrong", funfacts: [{id:1, text:"Sam initially gets his name confused with the Transformer, Megatron"}] },
    
    //GADREEL
    {name:"Gadreel",id:"gadreel",type:"angel", description:"The angel who accidentally let Lucifer into the Garden. Desperate for redemption, he possesses Sam and tries to do good, but is manipulated by Metatron. He eventually sacrifices himself.",imgsrc:"/assets/characters/gadreel.gif",species:"Angel",status:"Dead",occupation:"(Former) Guardian of Eden",age:"Ancient",nicknames:"Zeke(Dean), The Original Chump (Crowley)",relationships:"God (Father), Angels (Siblings)",catchphrase:"",strengths:"Loyalty, Healing, Deception",weaknesses:"Holy Oil, Supernatural Handcuffs, Angel Blade",quotes:[{id:1,text:"I am the protector you never knew you had."},{id:2,text:"I must atone for my sins."}],totalDeaths:1,deaths:[{id:1,text:"Committed Suicide to help Castiel escape Heaven's Jail."}], actor:"Tahmoh Penikett", funfacts:[{id:1, text:"He is originally a follower of Metatron, but ultimately helps Castiel defeat him after Metatron starts an angel suicide bombing campaign"}, {id:2, text:"He possesses Sam to help him heal and to get a new vessel."}, {id:3, text:"Metatron calls him Heaven's longest running joke."}]},
    
    //HANNAH
    {name:"Hannah",id:"hannah",type:"angel", description:"An angel who works closely with Castiel to restore order in Heaven. She values rules but begins to understand humanity more through Castiel.", imgsrc:"/assets/characters/hannah.gif",species:"Angel",status:"Dead",occupation:"Leader of Heaven",age:"Ancient",nicknames:"",relationships:"God (Father), Angels (Siblings)",catchphrase:"",strengths:"Angel powers, healing, combat",weaknesses:"Free will conflicts, Holy Oil, Supernatural Handcuffs, Angel Blade",quotes:[{id:1,text:"We always said humans were the original mission. We should put the humans first."}],totalDeaths:1,deaths:[{id:1, text:"Killed by Efram"}], actor:"Erica Carroll", funfacts:[{id:1, text:"Her first vessel's name is Caroline Johnson"}, {id:2, text:"She feels Caroline's longing for her husband and decides to occupy another vessel."}, {id:3, text:"Hannah's second vessel was a male."}, {id:4, text:"Switching vessels allowed Caroline to be one of a few humans to survive angel possession."}]},
    
    //MICHAEL
    {name:"Michael",id:"michael",type:"angel", description:"The oldest archangel and Heaven’s golden boy. In the main universe, he wants to use Dean as a vessel. In the alternate universe, he’s a cold, calculating conqueror.", imgsrc:"/assets/characters/michael.gif",species:"Archangel",status:"Dead",occupation:"Archangel, Warrior of Heaven",age:"Ancient",nicknames:"",relationships:"God (Father), Lucifer (brother), Gabriel (brother), Angels (Siblings)",catchphrase:"",strengths:"Strength, Intelligence, Leadership",weaknesses:"Family conflicts",quotes:[{id:1,text:"I just want to burn each and every one of his little worlds until I catch up with the old man."},{id:2,text:"I killed my Lucifer, tore him apart in the skies over Abilene. but hey, you can't get enough of a good thing."}, {id:3, text:"Humans, monsters, even angels are instects, atoms compared to us!"}],totalDeaths:1,deaths:[{id:1, text:"Killed by God."}],actor:"Jake Abel", funfacts: [{id:1, text:"Michael has 5 different vessels throughout the series."}]},
    
    //index 25: zachariah
    {name:"Zachariah",id:"zachariah",type:"angel", description:"A manipulative angel who sees the Winchesters as pawns. He believes the ends justify the means and doesn’t care who gets hurt to bring about the apocalypse.", imgsrc:"/assets/characters/zachariah.gif",species:"Angel",status:"Dead",occupation:"High-ranking Angel of Heaven",age:"Ancient",nicknames:"Zachariah",relationships:"God (Father), Amara (Aunt), Angels (Siblings)",catchphrase:"You will do as Heaven commands.",strengths:"Angel powers, manipulation",weaknesses:"Holy Oil, Supernatural Handcuffs, Angel Blade",quotes:[{id:1,text:"I serve Heaven’s will."},{id:2,text:"Obedience is strength."}],totalDeaths:1,deaths:[{id:1,text:"Killed by Castiel"}],funfacts:[{id:1, text:"Tried to force the apocalypse to happen, died resisting rebellion."}],actor:"Kurt Fuller"},
    
    //ANNA MILTON
    {name:"Anna Milton",id:"anna",type:"angel", description:"A fallen angel who chose to become human. She questions Heaven’s authority and tries to stop the apocalypse by killing Sam. Her arc is tragic and conflicted.", imgsrc:"/assets/characters/anna.gif",species:"Human/Angel",status:"Dead",occupation:"",age:"Ancient",nicknames:"",relationships:"God (Father), Amara (Aunt), Angels (Siblings)",catchphrase:"Free will is a curse and a blessing.",strengths:"Angel powers, free will, healing",weaknesses:"Heaven's laws/following orders, Holy Oil, Supernatural Handcuffs, Angel Blade",quotes:[{id:1,text:"I chose to fall to be free."},{id:2,text:"I will not be a pawn."}, {id: 3, text: 'First words I heard were as clear as a bell. Dean Winchester is saved.'}],totalDeaths:1,deaths:[{id:1, text:"Killed by Michael"}], actor:"Julie McNiven", funfacts:[{id:1, text:"Fell from grace to live a human life and fight Heaven’s control."}, {id:2, text:"She tries to go back in time to kill Sam and John Winchester, but is unsuccessful."}]},
    
    //AMARA
    { name: "Amara", id: "amara", type:"angel", description:"God’s sister and the embodiment of primordial chaos. She starts as a destructive force but evolves into a more complex being who just wants to be understood. Her bond with Dean is deep and strange.", imgsrc: "/assets/characters/amara.gif", species: "Deity", status: "Alive", occupation: "", age: "Primordial", nicknames: "The Darkness, Sister of God", relationships: "God (brother)", catchphrase: "I am the end and the beginning.", strengths: "Immense cosmic power, reality manipulation", weaknesses: "Divine intervention, family ties", quotes: [{ id: 1, text: "You cannot hide from the darkness." }, { id: 2, text: "I am older than time itself." }], totalDeaths: 0, deaths: [], actor: "Emily Swallow", funfacts: [{id:1, text:"She was confined to the Mark and holds a special bond with those who have it"}, {id:2, text:"She brings back Mary after Sam and Dean help restore her relationship with her brother."}] },

    //CHUCK
    {name: "Chuck Shurley", id: "chuck", type:"angel", description:"Originally introduced as a prophet, he’s eventually revealed to be God. Chuck is both creator and destroyer, becoming the final antagonist. His need for control and storytelling puts him at odds with the Winchesters.", imgsrc: "/assets/characters/chuck.gif", species: "Prophet / God", status: "Dead", occupation: "Writer", age: "Primordial", nicknames: "Carver Edlund", relationships: "Angels (creations), Humans (creations), Becky (ex-girlfriend), Amara (sister)", catchphrase: "", strengths: "Omniscience, Reality manipulation", weaknesses: "Prideful", quotes: [{id: 1, text: "No doubt, endings are hard. But then again, nothing really ever ends, does it?"}, {id: 2, text: "You know what huamnity's greatest creation has been? Music. That and nacho cheese. Even I couldn't have dreamt up that deliciousness."}], totalDeaths: 1, deaths: [{id: 1, text: "Killed by God (his true self)"}], actor: "Rob Benedict", funfacts:[{id:1, text:"He created a special gun called \"The Equalizer\""}, {id:2, text:"He hints that he is a \"cruel, capricious god\" in his first encounter with the Winchesters, but they don't believe him."}]},

    //JACK KLINE
    { name: "Jack Kline", id: "jack", type:"angel", description:"Lucifer’s Nephilim son, born of a human mother. Despite his heritage, Jack is kind and wants to do good. He becomes like a son to Sam, Dean, and Castiel. His journey is about choosing his own destiny.", imgsrc: "/assets/characters/jack.gif", species: "Nephilim", status: "Alive", occupation: "Hunter, God/Ruler of Heaven", age: "Teen", nicknames: "The Son of Lucifer, The Abomination", relationships: "Lucifer (Father), Kelly (Mother), Castiel (Guardian)", catchphrase: "", strengths: "Powerful angelic abilities, Healing, Strength", weaknesses: "Inexperience, Emotional struggles", quotes: [{ id: 1, text: "I want to be good." }, { id: 2, text: "I'm still learning who I am." }, {id:3, text:"Everytime I try and do something good, people get hurt."}], totalDeaths: 0, deaths: [], actor: "Alexander Calvert", funfacts:[{id:1, text:"While Lucifer is his father, Rowena and others mention that Jack has three fathers- Sam, Dean, and Castiel."}, {id:2, text:"Jack loves to eat candy bars with Nougat in them."}, {id:3, text:"His eyes are golden when his powers activate"}] },

    //DEATH AND REAPERS
    //BILLIE
    { name: "Billie", id: "billie", type:"reaper", description:"After the original Death is killed, Billie takes over the role. She believes in balance and cosmic order. At times an ally, at times an enemy, Billie always puts the natural order above individual lives—even the Winchesters'.", imgsrc: "/assets/characters/billie.gif", species: "Reaper", status: "Dead", occupation: "Death, (former) Reaper ", age: "Immortal", nicknames: "", relationships: "Reapers (subbordinates), Death (former boss)", catchphrase: "Death is not the end.", strengths: "Control over life and death, reaping souls", weaknesses: "Rules of Death, cosmic balance", quotes: [{ id: 1, text: "You think you're the only ones who can cheat death?" }, { id: 2, text: "Death always wins." }, {id:3, text:"I'm just going to make sure that when you die, you stay dead."}], totalDeaths: 2, deaths: [{id:1, text:"Stabbed by Castiel"},{id:2, text:"Killed by the Shadow"}], actor: "Lisa Berry", funfacts:[{id:1, text:"After becoming Death, she plots the destruction of God and the Darkness so she can take over the universe."}] },


    
];

// Alphabetize by character name
characters.sort((a, b) => a.name.localeCompare(b.name));