//takes title, imgsrc, description, majorUpdates, characterIntros, epNumbers, yearAired, ratings, bodyCount
export const episodes = [
    //Season One:
    {
        num:1, title: "Season One", imgsrc:"/assets/seasons/season1.jpg", photo:"/assets/titlecards/s1.gif", 
        description:"Brothers Sam and Dean Winchester reunite after years apart when their father goes missing during a hunting trip. As they travel across the country battling urban legends and supernatural creatures, they uncover clues about their family’s tragic past and the demon responsible for their mother’s death. The main conflict revolves around locating their father and confronting the Yellow-Eyed Demon, Azazel, who is revealed to be connected to a sinister plan involving Sam.", 
        majorUpdates: [{id: "dean", name:"Dean Winchester", text:"Critically injured in a car accident "}], 
        characterIntros: [{id:"dean", name:"Dean Winchester",text:"A loyal, battle-ready hunter searching for their missing father."}, {id:"sam", name:"Sam Winchester",text:"A reluctant hunter drawn back in after his girlfriend’s death."}, {id:"john", name:"John Winchester",text:"A missing hunter whose quest for revenge drives the story."}, ], 
        epNumbers: "22", yearAired: "2005", ratings:"8.5", bodyCount: "" , 
        epInfo: [
            {id: "s1e1", title:"Pilot", num: "1", photo: "", description: "Two brothers witness their mother's paranomal death and are trained to fight by their father, who aim to hunt down the thing that killed his wife."},
            {id: "s1e2", title:"Wendigo",num: "2", photo: "", description: "Sam and Dean follow the coordinates in their father's journal and land in Colorado, where they investigate the disappearance of several campers."},
            {id: "s1e3", title:"Dead in the Water",num: "3", photo: "", description: "In a small town in Wisconsin, Sam and Dean investigate a series of mysterious drownings officially explained as suicides."},
            {id: "s1e4", title:"Phantom Traveler",num: "4", photo: "", description: "On United Britannia flight 2485, a man possessed by the spirit of the Phantom Traveler causes the plane to crash, leaving only seven survivors."},
            {id: "s1e5", title:"Bloody Mary",num: "5", photo: "", description: "Several high schoolers dare their friend to look into a mirror and repeat a chant, not knowing that this will unleash a series of mysterious murders."},
            {id: "s1e6", title:"Skin",num: "6", photo: "", description: "Sam and Dean help Sam's old college buddy after he is accused of a murder he swears he didn't commit."},
            {id: "s1e7", title:"Hookman",num: "7", photo: "", description: "In a small town in Iowa, Sam and Dean encounter the infamous \"Hook Man,\" a spirit who kills his victims with a shiny hook that serves as his hand."},
            {id: "s1e8", title:"Bugs",num: "8", photo: "", description: "Sam and Dean investigate a town's history and find that a new housing development is being built on sacred Native American land."},
            {id: "s1e9", title:"Home",num: "9", photo: "", description: "Sam is haunted by a vision of a woman trapped in the brothers' childhood home and convinces a reluctant Dean that they need to go back there."},
            {id: "s1e10", title:"Asylum",num: "10", photo: "", description: "Sam and Dean investigate an abandoned sanitarium and discover the patients had revolted against the cruel punishments inflicted by the head doctor."},
            {id: "s1e11", title:"Scarecrow",num: "11", photo: "", description: "Sam and Dean finally make contact with their father, but he tells them to stop looking for him and sends them on another ghost-hunting job."},
            {id: "s1e12", title:"Faith",num: "12", photo: "", description: "While battling a demon, Dean is electrocuted, resulting in permanent damage to his heart and leaving him with only a couple months to live."},
            {id: "s1e13", title:"Route 666",num: "13", photo: "", description: "Dean is contacted by his first love, Cassie, a girl who asks him to come to Mississippi to investigate a string of racially motivated murders."},
            {id: "s1e14", title:"Nightmare",num: "14", photo: "", description: "Sam has a premonition in which a man is killed, but the murder is made to look like a suicide."},
            {id: "s1e15", title:"The Benders",num: "15", photo: "", description: "Sam and Dean head to Minnesota, where a young boy witnesses a man vanishing into thin air."},
            {id: "s1e16", title:"Shadow",num: "16", photo: "", description: "While investigating a mysterious death in Chicago, Sam and Dean run into Meg, who is thrilled to see Sam again."},
            {id: "s1e17", title:"Hell House",num: "17", photo: "", description: "Sam and Dean investigate a house haunted by the ghost of a man who killed his six daughters during the 1930s."},
            {id: "s1e18", title:"Something Wicked this Way Comes",num: "18", photo: "", description: "Sam and Dean investigate a small town in Wisconsin where children are falling into comas for no apparent reason."},
            {id: "s1e19", title:"Provenance",num: "19", photo: "", description: "A young husband and wife are killed in their home shortly after buying an antique painting of a family portrait from around 1910."},
            {id: "s1e20", title:"Dead Man's Blood",num: "20", photo: "", description: "After a vampire hunter who was John's mentor is murdered, Sam and Dean are surprised when John himself shows up to solve the case."},
            {id: "s1e21", title:"Salvation",num: "21", photo: "", description: "After Sam has a vision of a family being attacked, the brothers and their father head to Salvation, Iowa, to save the family in Sam's dream."},
            {id: "s1e22", title:"Devil's Trap",num: "22", photo: "", description: "On a mission to save their father from Meg, Sam and Dean seek help from an old family friend."}
        ]

    },
    {
        num:2,title: "Season Two", imgsrc:"/assets/seasons/season2.jpg", photo:"/assets/titlecards/s2.gif",
        description:"Following their father’s death and the revelation of Azazel’s plans, Sam and Dean continue hunting while struggling with the emotional fallout. Sam begins to exhibit strange powers, and they encounter others like him—children with psychic abilities also targeted by Azazel. As the brothers try to stop a demonic war from unfolding, they face the loss of friends and family. Azazel remains the key antagonist, orchestrating a deadly contest that pits the special children against each other.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2006", ratings:"8.6", bodyCount: "" , 
        epInfo: [
            {id: "s2e1", title:"In My Time of Dying",num: "1", photo: "", description: "Sam, Dean and John were left for dead after the Demon plowed a truck into the Impala. Now the surviving family members must face a powerful adversary."},
            {id: "s2e2", title:"Everybody Loves a Clown",num: "2", photo: "", description: "After listening to a message on John's cell phone from a woman named Ellen, Sam and Dean decide to track her down."},
            {id: "s2e3", title:"Bloodlust",num: "3", photo: "", description: "Sam and Dean encounter Gordon, a fellow demon hunter who has been systematically killing vampires in a small town."},
            {id: "s2e4", title:"Children Shouldn't Play with Dead Things",num: "4", photo: "", description: "Sam and Dean investigate the murder of a college student who has come back from the dead seeking revenge on those who mistreated her."},
            {id: "s2e5", title:"Simon Said",num: "5", photo: "", description: "Sam and Dean meet Andy, a slacker who has psychic powers of persuasion that he uses to gain favors from people."},
            {id: "s2e6", title:"No Exit",num: "6", photo: "", description: "Sam and Dean investigate the brutal slayings of blonde women from the same apartment building."},
            {id: "s2e7", title:"The Usual Suspects",num: "7", photo: "", description: "Sam and Dean investigate the murder of a lawyer and his wife. Right before they died, they claimed they'd seen a ghost."},
            {id: "s2e8", title:"Crossroad Blues",num: "8", photo: "", description: "When two highly successful professionals die after claiming to be haunted by hellhounds, Sam and Dean investigate a local bar."},
            {id: "s2e9", title:"Croatoan",num: "9", photo: "", description: "When Sam has a vision of Dean killing a young man who seems to be possessed by a demon, the two brothers head to Oregon to search for answers."},
            {id: "s2e10", title:"Hunted",num: "10", photo: "", description: "After Dean tells Sam what their father told him right before he died, the distraught Sam sneaks off to Indiana alone."},
            {id: "s2e11", title:"Playthings",num: "11", photo: "", description: "Sam and Dean investigate two strange deaths at a small Conneticut inn run by a single mom whose young daughter plays with an imaginary friend."},
            {id: "s2e12", title:"Night Shifter",num: "12", photo: "", description: "Sam and Dean investigate a string of robberies with a disturbing pattern."},
            {id: "s2e13", title:"Houses of the Holy",num: "13", photo: "", description: "Sam and Dean investigate the murders of several people by individuals who claim they were visited by an angel and were carrying out God's will."},
            {id: "s2e14", title:"Born Under a Bad Sign",num: "14", photo: "", description: "After receiving a frantic call from Sam, who has been missing for more than a week, Dean races to his brother's side."},
            {id: "s2e15", title:"Tall Tales",num: "15", photo: "", description: "Sam and Dean call on their friend Bobby for help after they are stumped by violent and inexplicable happenings on a local college campus."},
            {id: "s2e16", title:"Roadkill",num: "16", photo: "", description: "While driving down a deserted road, Sam and Dean are startled when a bloody woman runs in front of the Impala, screaming for help."},
            {id: "s2e17", title:"Heart",num: "17", photo: "", description: "While investigating the death of a lawyer, who appeared to have been killed by a wild animal, Sam and Dean realize they are tracking a werewolf."},
            {id: "s2e18", title:"Hollywood Babylon",num: "18", photo: "", description: "Sam and Dean travel to Hollywood to investigate the death of an actor on a horror film set after rumors spread that he was killed by a ghost."},
            {id: "s2e19", title:"Folsom Prison Blues",num: "19", photo: "", description: "After hearing about a ghost that has been killing off prison inmates one by one, Sam and Dean decide the best way to investigate is from the inside."},
            {id: "s2e20", title:"What Is and What Should Never Be",num: "20", photo: "", description: "While hunting a djinn, or genie, Dean is attacked and transported to an alternate world."},
            {id: "s2e21", title:"All Hell Breaks Loose: Part 1",num: "21", photo: "", description: "Sam is abducted by the yellow-eyed demon and finds himself in a ghost town with children who have special abilities."},
            {id: "s2e22", title:"All Hell Breaks Loose: Part 2",num: "22", photo: "", description: "While dealing with the aftermath of the fight between Sam and Jake, Dean pays a steep price for his involvement."}
        ]

    },
    {
        num:3,title: "Season Three", imgsrc:"/assets/seasons/season3.jpg", photo:"/assets/titlecards/s3.gif",
        description:"After making a deal with a crossroads demon to save Sam’s life, Dean has one year left to live before going to Hell. The brothers desperately search for a way to break the contract. Their quest is made harder by the rise of new threats, including demons freed from Hell by Azazel’s death. Among these is Lilith, a powerful demon who holds Dean’s contract and is systematically eliminating psychic children like Sam.",
        majorUpdates: [{id:"", name:"", text:""}], 
        //Lisa/Ben, Gabriel
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "16", yearAired: "2007", ratings:"8.4", bodyCount: "" , 
        epInfo: [
            {id: "s3e1", title:"The Magnificent Seven",num: "1", photo: "", description: "Sam and Dean realize they have an enormous task: hunting down the hundreds of demons that escaped from the Devil's Gate."},
            {id: "s3e2", title:"The Kids are Alright",num: "2", photo: "", description: "Dean pressures Sam into traveling to Cicero, Ind., so Dean can visit an old flame named Lisa, with whom he had a tryst nine years ago."},
            {id: "s3e3", title:"Bad Day at Black Rock",num: "3", photo: "", description: "Sam and Dean answer a call on their father's old cell phone, alerting them that someone has broken into their dad's secret storage room in New York."},
            {id: "s3e4", title:"Sin City",num: "4", photo: "", description: "Sam and Dean investigate a rash of violent deaths in Elizabethville, Ohio, a once-sleepy town that has become a haven for gamblers and drinkers."},
            {id: "s3e5", title:"Bedtime Stories",num: "5", photo: "", description: "Sam and Dean investigate a small town that has been plagued by a number of strange murders mimicking fairy tales."},
            {id: "s3e6", title:"Red Sky at Morning",num: "6", photo: "", description: "Sam and Dean investigate the mysterious demise of drowning victims who were nowhere near water at the time of their death."},
            {id: "s3e7", title:"Fresh Blood",num: "7", photo: "", description: "Sam and Dean capture a female vampire named Lucy who claims to have no knowledge of how she became a vampire."},
            {id: "s3e8", title:"A Very Supernatural Christmas",num: "8", photo: "", description: "It's Christmastime, and Sam and Dean investigate a series of murders where the victims were pulled up through chimneys."},
            {id: "s3e9", title:"Malleus Maleficarum",num: "9", photo: "", description: "Sam and Dean travel to Sturbridge, Mass., and discover a coven of witches that has killed two people."},
            {id: "s3e10", title:"Dream a Little Dream of Me",num: "10", photo: "", description: "When Bobby falls into a coma and can't be awakened, Sam and Dean race to his side."},
            {id: "s3e11", title:"Mystery Spot",num: "11", photo: "", description: "While Sam and Dean are investigating the disappearance of a man from a tourist location, Dean is shot and killed."},
            {id: "s3e12", title:"Jus in Bello",num: "12", photo: "", description: "Sam and Dean break into Bela's apartment in order to get the Colt back, but she has tipped off Agent Henriksen to their whereabouts."},
            {id: "s3e13", title:"Ghostfacers!",num: "13", photo: "", description: "Sam and Dean stumble into starring roles on a gritty reality show called \"Ghostfacers,\" which chronicles the pursuit of the paranormal."},
            {id: "s3e14", title:"Long-Distance Call",num: "14", photo: "", description: "Dean is stunned to receive a phone call from his dad, who says he has a solution to get Dean out of his deal."},
            {id: "s3e15", title:"Time is on My Side",num: "15", photo: "", description: "As time runs out for Dean, Sam convinces him to head to Erie, Pa., to investigate a possible zombie case."},
            {id: "s3e16", title:"No Rest for the Wicked",num: "16", photo: "", description: "In a battle to the death, Sam, Dean, and Bobby take on Lilith and all her demons in a last-ditch effort to save Dean's life."},
        ]

    },
    {
        num:4,title: "Season Four", imgsrc:"/assets/seasons/season4.jpg", photo:"/assets/titlecards/s4.gif",
        description:"Dean is miraculously saved from Hell by Castiel, an angel who brings word of an impending apocalypse. Heaven and Hell wage war on Earth, using humanity as pawns. As Sam becomes addicted to demon blood and aligns with a demon named Ruby, the brothers’ trust fractures. The season builds to a devastating finale in which Lilith’s death—at Sam’s hands—releases Lucifer from his prison, setting the stage for the apocalypse.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2008", ratings:"8.5", bodyCount: "" , 
        epInfo: [
            {id: "s4e1", title:"Lazarus Rising",num: "1", photo: "", description: "Dean wakes up in a pine box, freed from Hell. He has a joyful reunion with Sam, but they wonder what pulled Dean from Hell- and why."},
            {id: "s4e2", title:"Are You There, God? It's Me, Dean Winchester",num: "2", photo: "", description: "Sam and Dean are stunned when the spirits of Meg and Agent Henricksen appear."},
            {id: "s4e3", title:"In the Beginning",num: "3", photo: "", description: "Dean is transported back in time and finds that his newfound grandfather may be hiding a secret that is key to Sam and Dean's predicament."},
            {id: "s4e4", title:"Metamorphosis",num: "4", photo: "", description: "Sam and Dean find that a family man is turning into a flesh-eating monster, and they argue about killing him."},
            {id: "s4e5", title:"Monster Movie",num: "5", photo: "", description: "Dean and Sam investigate murders at Oktoberfest. Dean determines a shape-shifter demon is appearing as iconic monsters from old Hollywood movies."},
            {id: "s4e6", title:"Yellow Fever",num: "6", photo: "", description: "Dean is infected with an illness that starts as anxiety, but moves to full-blown terror and stops the heart."},
            {id: "s4e7", title:"It's the Great Pumpkin, Sam Winchester",num: "7", photo: "", description: "The brothers deduce a witch is sacraficing people to summon a dangerous demon. Robert Wisdom guest stars as Uriel, a specialist angel."},
            {id: "s4e8", title:"Wishful Thinking",num: "8", photo: "", description: "Sam and Dean investigate a small town where a wishing well actually works. The brothers realize, however, that the end result could be disastrous."},
            {id: "s4e9", title:"I Know What You Did Last Summer",num: "9", photo: "", description: "Ruby, Sam and Dean look for a girl who hears the angels. Castiel and Uriel return."},
            {id: "s4e10", title:"Heaven and Hell",num: "10", photo: "", description: "Anna recalls her past and Sam and Dean understand why Castiel and Uriel want her dead."},
            {id: "s4e11", title:"Family Remains",num: "11", photo: "", description: "Sam and Dean investigate the appearance of a young female ghost in an abandoned house, but things become more complicated when a family moves in."},
            {id: "s4e12", title:"Criss Angel is a Douche Bag",num: "12", photo: "", description: "Barry Bostwick, John Rubinstein and Richard Libertini guest star as three friends who used to be famous magicians, but have since been replaced."},
            {id: "s4e13", title:"After School Special",num: "13", photo: "", description: "Sam and Dean go undercover at their old high school, causing them to flash back to when Sam was picked on by the school bully and Dean was popular."},
            {id: "s4e14", title:"Sex and Violence",num: "14", photo: "", description: "Sam and Dean find three small-town men have beaten their wives to death. Behind the murders is a siren, who puts the brothers under her spell."},
            {id: "s4e15", title:"Death Takes a Holiday",num: "15", photo: "", description: "Pamela sends the boys to the spiritual world when they find people cheating death. They must face Alastair, who is kidnapping the Reapers."},
            {id: "s4e16", title:"On the Head of a Pin",num: "16", photo: "", description: "Castiel and Uriel capture Alastair, and ask Dean to torture him with skills he learned in Hell."},
            {id: "s4e17", title:"It's a Terrible Life",num: "17", photo: "", description: "What if the Winchesters weren't hunters? In this alternative life, Dean is a corporate man who enjoys health drinks and Sam is in tech support."},
            {id: "s4e18", title:"The Monster at the End of This Book",num: "18", photo: "", description: "Sam and Dean discover \"Supernatural,\" a series of books that accurately detail their lives as demon hunters."},
            {id: "s4e19", title:"Jump the Shark",num: "19", photo: "", description: "A 19 year old boy named Adam calls Sam and Dean looking for John Winchester; the boy claims to be his son."},
            {id: "s4e20", title:"The Rapture",num: "20", photo: "", description: "Dean and Sam search for Castiel, who appeared to Dean in a dream. Instead, they find Castiel's human vessel, who has little memory of being an angel."},
            {id: "s4e21", title:"When the Levee Breaks",num: "21", photo: "", description: "Dean and Bobby lock Sam in Bobby's panic room so he can detox from the demon blood. Sam and Dean have a big blowout confrontation."},
            {id: "s4e22", title:"Lucifer Rising",num: "22", photo: "", description: "Sam and Dean prepare for the apocalypse in different ways. Ruby, Lilith, Castiel, and Zachariah appear."}
        ]

    },
    {
        num:5,title: "Season Five", imgsrc:"/assets/seasons/season5.jpg", photo:"/assets/titlecards/s5.gif",
        description:"Lucifer is free, and the apocalypse is in full swing. Sam and Dean learn they are destined to become vessels for Lucifer and Michael in a final, world-ending showdown. While resisting fate, they search for a way to trap Lucifer again, eventually using the Four Horsemen’s rings to open the cage. With sacrificial courage, Sam takes Lucifer back into the cage, ending the apocalypse. Lucifer is the main antagonist, driving the conflict between destiny and free will.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2009", ratings:"8.8", bodyCount: "" , 
        epInfo: [
            {id: "s5e1", title:"Sympathy for the Devil",num: "1", photo: "", description: "Dean and Sam watch as the devil emerges from hell and must deal with the aftermath."},
            {id: "s5e2", title:"Good God, Y'all!",num: "2", photo: "", description: "While Castiel goes in search of God in the fight against Lucifer, Sam and Dean help an older hunter friend of Bobby's."},
            {id: "s5e3", title:"Free to Be You and Me",num: "3", photo: "", description: "Not sure he trusts himself anymore, Sam decides to give up hunting. Meanwhile, Dean teams up with Castiel to find the Archangel Raphael."},
            {id: "s5e4", title:"The End",num: "4", photo: "", description: "Dean gets a glimpse of the future in which humans have been infected with a demonic virus that turns them into zombies."},
            {id: "s5e5", title:"Fallen Idols",num: "5", photo: "", description: "Sam and Dean reunite to investigate a small town whose inhabitants are being killed by famous dead people."},
            {id: "s5e6", title:"I Believe the Children Are Our Future",num: "6", photo: "", description: "Investigating a series of odd murders that resemble fairy tales and urban legends, Sam and Dean track down a dangerous boy named Jesse."},
            {id: "s5e7", title:"The Curious Case of Dean Winchester",num: "7", photo: "", description: "Sam and Dean play a high-stakes poker game with a witch, where the currency is life years-- not money."},
            {id: "s5e8", title:"Changing Channels",num: "8", photo: "", description: "Sam and Dean get stuck in TV Hell when the Trickster imprisons them in an alternate universe."},
            {id: "s5e9", title:"The Real Ghostbusters",num: "9", photo: "", description: "Sam and Dean attend a \"Supernatural\" fan convention-- complete with fans dressed up as Sam and Dean."},
            {id: "s5e10", title:"Abandon All Hope",num: "10", photo: "", description: "It's a hunters' reunion when Sam and Dean face off against Lucifer with the help of Castiel, Bobby, Ellen and Jo."},
            {id: "s5e11", title:"Sam, Interrupted",num: "11", photo: "", description: "Sam and Dean check into a mental hospital to investigate a mysterious monster that's been attacking the patients."},
            {id: "s5e12", title:"Swap Meat",num: "12", photo: "", description: "A teenage nerd conjures up a body-switching spell and changes bodies with Sam."},
            {id: "s5e13", title:"The Song Remains the Same",num: "13", photo: "", description: "The angels go back in time to kill John and Mary Winchester before they can conceive Sam."},
            {id: "s5e14", title:"My Bloody Valentine",num: "14", photo: "", description: "Castiel helps Sam and Dean hunt down Cupid on Valentine's Day after people begin killing each other for love."},
            {id: "s5e15", title:"Dead Men Don't Wear Plaid",num: "15", photo: "", description: "The dead are rising from their graves and happily reuniting with their families in Bobby's hometown."},
            {id: "s5e16", title:"Dark Side of the Moon",num: "16", photo: "", description: "Ambushed by angry hunters, Sam and Dean are shot and killed and sent to heaven!"},
            {id: "s5e17", title:"99 Problems",num: "17", photo: "", description: "Outnumbered by demons,  Sam and Dean are saved at the last minute by a hunter and his very religious townspeople."},
            {id: "s5e18", title:"Point of No Return",num: "18", photo: "", description: "When Dean learns that the angels have decided they don't need him anymore, he joins with Sam and Castiel to take on Zachariah."},
            {id: "s5e19", title:"Hammer of the Gods",num: "19", photo: "", description: "Sam and Dean are held hostage by a group of gods who want to use them as bargaining chips to stop the Apocalypse."},
            {id: "s5e20", title:"The Devil You Know",num: "20", photo: "", description: "The demon Crowley offers to help Sam and Dean find the remaining Horsemen by leading them to the Handler for Pestilence and Death."},
            {id: "s5e21", title:"Two Minutes to Midnight",num: "21", photo: "", description: "Bobby sells his soul to the demon Crowley in exchange for the location of the Fourth Horseman."},
            {id: "s5e22", title:"Swan Song",num: "22", photo: "", description: "With the Apocalypse looming in a showdown between good and evil, Sam and Dean realize they are out of options."}
        ]

    },
    {
        num:6,title: "Season Six", imgsrc:"/assets/seasons/season6.jpg", photo:"/assets/titlecards/s6.gif",
        description:"The aftermath of the apocalypse leaves the supernatural world in chaos. Sam returns mysteriously from Hell—soulless and emotionally void. Dean, trying to settle into normal life, is pulled back into hunting as new threats emerge, including creatures created by Eve, the Mother of All Monsters. As they face increasingly strange beings, the brothers uncover a plot involving the souls of Purgatory, manipulated by Castiel in his quest to stop Raphael’s plans for another apocalypse.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2010", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s6e1", title:"Exile on Main St.",num: "1", photo: "", description: "Mysteriously freed from hell, Sam finds Dean and tells him he needs to rejoin the fight."},
            {id: "s6e2", title:"Two and a Half Men",num: "2", photo: "", description: "Sam investigates a case involving missing babies whose parents are being murdered."},
            {id: "s6e3", title:"The Third Man",num: "3", photo: "", description: "Investigating a case of biblical plagues, Sam and Dean call Castiel for help and learn that God's weapons have been stolen."},
            {id: "s6e4", title:"Weekend at Bobby's",num: "4", photo: "", description: "After Bobby discovers that Crowley has no intention of returning Bobby's soul, the hunter takes matters into his own hands."},
            {id: "s6e5", title:"Live Free or Twi-hard",num: "5", photo: "", description: "After fighting a group of vampires, Dean is bitten and turns into a vampire."},
            {id: "s6e6", title:"You Can't Handle the Truth",num: "6", photo: "", description: "Sam and Dean investigate a series of suicides and discover that someone is invoking the Goddess of Truth, forcing people to be cruelly honest."},
            {id: "s6e7", title:"Family Matters",num: "7", photo: "", description: "Dean becomes suspicious of Samuel's motives when the brothers go along on a hunt with their grandfather and the other Campbells and thigns go awry."},
            {id: "s6e8", title:"All Dogs Go to Heaven",num: "8", photo: "", description: "Sent to investigate an apparent werewolf attack, Dean and Sam follow the clues to a mother and son with an unusual dog."},
            {id: "s6e9", title:"Clap Your Hands if You Believe",num: "9", photo: "", description: "While Sam and Dean are investigatin a UFO sighting, Dean is abducted from a crop circle."},
            {id: "s6e10", title:"Caged Heart",num: "10", photo: "", description: "The demon Meg kidnaps Sam and Dean for information on Crowley. Sam offers to help her if she'll help get his soul back."},
            {id: "s6e11", title:"Appointment in Samarra",num: "11", photo: "", description: "Dean makes a deal with Death to help get Sam's soul back, but Sam decides that he doesn't want it back and enlists help to keep it that way."},
            {id: "s6e12", title:"Like a Virgin",num: "12", photo: "", description: "When Sam and Dean discover what's behind the disappearance of several virgins, they turn to an expert in medieval lore for help."},
            {id: "s6e13", title:"Unforgiven",num: "13", photo: "", description: "When Sam receives a mysterious text with coordinates to a small town, he starts to have flashbacks to an old case."},
            {id: "s6e14", title:"Mannequin 3: The Reckoning",num: "14", photo: "", description: "When Ben calls Dean and tells him that Lisa is in trouble, Dean leaves Sam to investigate a case alone and rushes to the rescue."},
            {id: "s6e15", title:"The French Mistake",num: "15", photo: "", description: "Sam and Dean are transported to an alternate reality, where they are the stars to a TV show called \"Supernatural.\""},
            {id: "s6e16", title:"...And Then There Were None",num: "16", photo: "", description: "In search of the Mother of All's latest monster, Sam, Dean, and Bobby run into Samuel and Gwen Campbell and fight about how to handle the case."},
            {id: "s6e17", title:"My Heart Will Go On",num: "17", photo: "", description: "Castiel tells Sam and Dean that Fate is very upset with the two of them and the only way they can stay alive is to kill her."},
            {id: "s6e18", title:"Frontierland",num: "18", photo: "", description: "Sam and Dean are sent back in time to the Wild West so they can meet Samuel Colt and ask him for his help in defeating Eve."},
            {id: "s6e19", title:"Mommy Dearest",num: "19", photo: "", description: "Sam, Dean, Bobby and Castiel track Eve to a small town in Oregon, where she's transforming the inhabitants into demons."},
            {id: "s6e20", title:"The Man Who Would Be King",num: "20", photo: "", description: "Castiel tells Sam, Dean and Bobby about the war in heaven and how he and Raphael became enemies."},
            {id: "s6e21", title:"Let it Bleed",num: "21", photo: "", description: "Dean's worst nightmare comes true when a demon kidnaps Ben and Lisa to get to him."},
            {id: "s6e22", title:"The Man Who Knew Too Much",num: "22", photo: "", description: "The wall comes down in Sam's mind and all hell breaks loose, while Dean and Bobby are powerless to help. The battle for heaven comes to a head."}
        ]

    },
    {
        num:7,title: "Season Seven", imgsrc:"/assets/seasons/season7.jpg", photo:"/assets/titlecards/s7.gif",
        description:"The Leviathans, ancient creatures predating angels and demons, escape from Purgatory and begin taking over human society. Led by the cunning Dick Roman, they aim to turn humanity into complacent, edible cattle. As Sam suffers hallucinations and Dean spirals into despair, the brothers struggle to find a way to stop beings that can’t be killed by conventional means. The Leviathans become the most difficult and alien threat they’ve faced yet.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2011", ratings:"8.0", bodyCount: "" , 
        epInfo: [
            {id: "s7e1", title:"Meet the New Boss",num: "1", photo: "", description: "Assuming his new role as God, Castiel sets out to right some of the wrongs in the world. And Dean decides to bind Death in order to stop him."},
            {id: "s7e2", title:"Hello, Cruel World",num: "2", photo: "", description: "While Castiel struggles with the burdens of his absolute power, the broken psychological wall in Sam's mind leaves him unable to discern what is real."},
            {id: "s7e3", title:"The Girl Next Door",num: "3", photo: "", description: "Dean is furious when Sam disappears to follow a case with clues identical to a case Sam solved as a kid. And Sam meets a demon he defeated years ago."},
            {id: "s7e4", title:"Defending Your Life",num: "4", photo: "", description: "Investigating a string of gruesome murders, Sam and Dean discover the vengeful Egyptian god Osiris, who puts Dean on trial for his past mistakes."},
            {id: "s7e5", title:"Shut Up, Dr. Phil",num: "5", photo: "", description: "Sam and Dean track down a witch who is taking out her wrath for her unfaithful husband on the entire town."},
            {id: "s7e6", title:"Slash Fiction",num: "6", photo: "", description: "Once again on the FBI's Most Wanted list, Sam and Dean seek help from a friend of Bobby's when two Leviathans go on a killing spree as Sam and Dean."},
            {id: "s7e7", title:"The Mentalists",num: "7", photo: "", description: "Sam and Dean investigate an angry spirit killing the resident mediums of Lily Dale, the most \"pyschic\" town in America."},
            {id: "s7e8", title:"Season 7, Time for a Wedding!",num: "8", photo: "", description: "While Sam is entangled with someone from his past, Dean reluctantly teams up with a quirky laidback hunter named Garth."},
            {id: "s7e9", title:"How to Win Friends and Influence Monsters",num: "9", photo: "", description: "Sam and Dean track the Jersey Devil, a creature suspected of attacking people in the woods, and encounter a monster sandwich with nasty side effects."},
            {id: "s7e10", title:"Death's Door",num: "10", photo: "", description: "Bobby seeks the help of an unlikely old friend to solve one of the most personal cases of his life."},
            {id: "s7e11", title:"Adventures in Babysitting",num: "11", photo: "", description: "While Dean becomes obsessed with eliminating Dick Roman, Sam helps a teenage girl look for her father, a hunter who's gone missing."},
            {id: "s7e12", title:"Time After Time",num: "12", photo: "", description: "The God of Time who sends Dean back to 1944, where he is immediately arrested by the legendary Eliot Ness who, surprisingly, is also a hunter."},
            {id: "s7e13", title:"The Slice Girls",num: "13", photo: "", description: "Dean's rendezvous with an Amazon warrior has serious complications."},
            {id: "s7e14", title:"Plucky Pennywhistle's Magic Menagerie",num: "14", photo: "", description: "Sam confronts his fear of clowns when he and Dean investigate a children's pizza chain that is manifesting children's worst (and deadliest) fears."},
            {id: "s7e15", title:"Repo Man",num: "15", photo: "", description: "Sam and Dean investigate the apparent reappearance of a demon they exorcised years ago."},
            {id: "s7e16", title:"Out with the Old",num: "16", photo: "", description: "Sam and Dean visit a town gone haywire after a large collection of cursed objects is mistakenly released."},
            {id: "s7e17", title:"The Born-Again Identity",num: "17", photo: "", description: "Desperate to save Sam from Lucifer, Dean calls every hunter for help, but instead meets a healer with a familiar face."},
            {id: "s7e18", title:"Party On, Garth",num: "18", photo: "", description: ""},
            {id: "s7e19", title:"Of Grave Importance",num: "19", photo: "", description: ""},
            {id: "s7e20", title:"The Girl with the Dungeons and Dragons Tattoo",num: "20", photo: "", description: ""},
            {id: "s7e21", title:"Reading is Fundamental",num: "21", photo: "", description: ""},
            {id: "s7e22", title:"There Will Be Blood",num: "22", photo: "", description: ""},
            {id: "s7e23", title:"Survival of the Fittest",num: "23", photo:"", description: ""}
        ]

    },
    {
        num:8,title: "Season Eight", imgsrc:"/assets/seasons/season8.jpg", photo:"/assets/titlecards/s8.gif",
        description:"After being trapped in Purgatory, Dean returns with a vampire ally, while Sam has tried to live a normal life. The brothers reunite to search for the Men of Letters' legacy, which leads them to the trials needed to close the gates of Hell permanently. As Sam completes each trial, it takes a physical toll on him. The season focuses on trust, sacrifice, and the brothers’ evolving roles. Abaddon, a resurrected Knight of Hell, emerges as a significant threat.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2012", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s8e1", title:"We Need to Talk About Kevin",num: "1", photo: "", description: ""},
            {id: "s8e2", title:"What's Up, Tiger Mommy?",num: "2", photo: "", description: ""},
            {id: "s8e3", title:"Heartache",num: "3", photo: "", description: ""},
            {id: "s8e4", title:"Bitten",num: "4", photo: "", description: ""},
            {id: "s8e5", title:"Blood Brother",num: "5", photo: "", description: ""},
            {id: "s8e6",title:"Southern Comfort", num: "6", photo: "", description: ""},
            {id: "s8e7", title:"A Little Slice of Kevin",num: "7", photo: "", description: ""},
            {id: "s8e8", title:"Hunter Heroici",num: "8", photo: "", description: ""},
            {id: "s8e9", title:"Citizen Fang",num: "9", photo: "", description: ""},
            {id: "s8e10", title:"Torn and Frayed",num: "10", photo: "", description: ""},
            {id: "s8e11", title:"LARP and the Real Girl",num: "11", photo: "", description: ""},
            {id: "s8e12", title:"As Time Goes By",num: "12", photo: "", description: ""},
            {id: "s8e13", title:"Everybody Hates Hitler",num: "13", photo: "", description: ""},
            {id: "s8e14", title:"Trial and Error",num: "14", photo: "", description: ""},
            {id: "s8e15", title:"Man's Best Friend with Benefits",num: "15", photo: "", description: ""},
            {id: "s8e16", title:"Remember the Titans",num: "16", photo: "", description: ""},
            {id: "s8e17", title:"Goodbye Stranger",num: "17", photo: "", description: ""},
            {id: "s8e18", title:"Freaks and Geeks",num: "18", photo: "", description: ""},
            {id: "s8e19", title:"Taxi Driver",num: "19", photo: "", description: ""},
            {id: "s8e20", title:"Pac-Man Fever",num: "20", photo: "", description: ""},
            {id: "s8e21", title:"The Great Escapist",num: "21", photo: "", description: ""},
            {id: "s8e22", title:"Clip Show",num: "22", photo: "", description: ""},
            {id: "s8e23", title:"Sacrafice",num:"23", photo:"", description:""}
        ]

    },
    {
        num:9,title: "Season Nine", imgsrc:"/assets/seasons/season9.jpg", photo:"/assets/titlecards/s9.gif",
        description:"With the gates of Heaven closed and angels cast out, chaos reigns. Dean, desperate to save a dying Sam, allows an angel named Gadreel to possess him, straining their relationship. Meanwhile, the Mark of Cain gives Dean incredible power at a cost. Metatron, Heaven’s former scribe, manipulates events to gain power and declare himself the new God. The season ends with Dean dying and resurrecting as a demon, thanks to the Mark.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2013", ratings:"8.0", bodyCount: "" , 
        epInfo: [
            {id: "s9e1", title:"I Think I'm Gonna Like It Here",num: "1", photo: "", description: ""},
            {id: "s9e2", title:"Devil May Care",num: "2", photo: "", description: ""},
            {id: "s9e3", title:"I'm No Angel",num: "3", photo: "", description: ""},
            {id: "s9e4", title:"Slumber Party",num: "4", photo: "", description: ""},
            {id: "s9e5", title:"Dog Dean Afternoon",num: "5", photo: "", description: ""},
            {id: "s9e6", title:"Heaven Can't Wait",num: "6", photo: "", description: ""},
            {id: "s9e7", title:"Bad Boys",num: "7", photo: "", description: ""},
            {id: "s9e8", title:"Rock and a Hard Place",num: "8", photo: "", description: ""},
            {id: "s9e9", title:"Holy Terror",num: "9", photo: "", description: ""},
            {id: "s9e10", title:"Road Trip",num: "10", photo: "", description: ""},
            {id: "s9e11", title:"First Born",num: "11", photo: "", description: ""},
            {id: "s9e12",title:"Sharp Teeth", num: "12", photo: "", description: ""},
            {id: "s9e13", title:"The Purge",num: "13", photo: "", description: ""},
            {id: "s9e14", title:"Captives",num: "14", photo: "", description: ""},
            {id: "s9e15", title:"#thinman",num: "15", photo: "", description: ""},
            {id: "s9e16", title:"Blade Runners",num: "16", photo: "", description: ""},
            {id: "s9e17", title:"Mother's Little Helper",num: "17", photo: "", description: ""},
            {id: "s9e18", title:"Meta Fiction",num: "18", photo: "", description: ""},
            {id: "s9e19", title:"Alex Annie Alexis Ann",num: "19", photo: "", description: ""},
            {id: "s9e20", title:"Bloodlines",num: "20", photo: "", description: ""},
            {id: "s9e21", title:"King of the Damned",num: "21", photo: "", description: ""},
            {id: "s9e22", title:"Stairway to Heaven",num: "22", photo: "", description: ""},
            {id: "s9e23", title:"Do You Believe in Miracles?",num: "22", photo: "", description: ""},
        ]

    },
    {
        num:10,title: "Season Ten", imgsrc:"/assets/seasons/season10.jpg", photo:"/assets/titlecards/s10.gif",
        description:"Dean battles the effects of the Mark of Cain, which turns him increasingly violent. Sam searches for a cure while Castiel deals with dwindling grace. Crowley’s alliances shift as the brothers clash with Rowena, a powerful witch and Crowley’s mother. The Mark’s true origin is revealed to be tied to an ancient entity called the Darkness. Removing the Mark unleashes this being, setting up an even more powerful adversary.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2014", ratings:"8.2", bodyCount: "" , 
        epInfo: [
            {id: "s10e1", title:"Black",num: "1", photo: "", description: ""},
            {id: "s10e2", title:"Reichenbach",num: "2", photo: "", description: ""},
            {id: "s10e3", title:"Paper Moon",num: "15", photo: "", description: ""},
            {id: "s10e4", title:"Soul Survivor",num: "3", photo: "", description: ""},
            {id: "s10e5", title:"Fan Fiction",num: "4", photo: "", description: ""},
            {id: "s10e6", title:"Ask Jeeves",num: "5", photo: "", description: ""},
            {id: "s10e7", title:"Girls, Girls, Girls",num: "6", photo: "", description: ""},
            {id: "s10e8", title:"Hibbing 911",num: "7", photo: "", description: ""},
            {id: "s10e9", title:"The Things We Left Behind",num: "8", photo: "", description: ""},
            {id: "s10e10", title:"The Hunter Games",num: "9", photo: "", description: ""},
            {id: "s10e11", title:"There's No Place Like Home",num: "10", photo: "", description: ""},
            {id: "s10e12", title:"About a Boy",num: "11", photo: "", description: ""},
            {id: "s10e13", title:"Halt & Catch Fire",num: "12", photo: "", description: ""},
            {id: "s10e14", title:"The Executioner's Song",num: "13", photo: "", description: ""},
            {id: "s10e15", title:"The Things They Carried",num: "14", photo: "", description: ""},
            {id: "s10e16", title:"Paint it Black",num: "16", photo: "", description: ""},
            {id: "s10e17", title:"Inside Man",num: "17", photo: "", description: ""},
            {id: "s10e18", title:"Book of the Damned",num: "18", photo: "", description: ""},
            {id: "s10e19", title:"The Werther Project",num: "19", photo: "", description: ""},
            {id: "s10e20", title:"Angel Heart",num: "20", photo: "", description: ""},
            {id: "s10e21", title:"Dark Dynasty",num: "21", photo: "", description: ""},
            {id: "s10e22", title:"The Prisoner",num: "22", photo: "", description: ""},
            {id: "s10e23", title:"Brother's Keeper",num: "22", photo: "", description: ""},
        ]
    },
    {
        num:11,title: "Season Eleven", imgsrc:"/assets/seasons/season11.jpg", photo:"/assets/titlecards/s11.gif",
        description:"The Darkness, now known as Amara, emerges and threatens to destroy the universe. She is God’s sister and seeks revenge for her imprisonment. As Amara grows in power, even angels and demons prove powerless. The Winchesters attempt to find God—revealed to be Chuck Shurley—and convince him to help. The season becomes a cosmic family drama between Chuck and Amara, leading to a fragile truce that restores balance to the universe.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2015", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s11e1", title:"Out of the Darkness, Into the Fire",num: "1", photo: "", description: ""},
            {id: "s11e2", title:"Form and Void",num: "2", photo: "", description: ""},
            {id: "s11e3", title:"The Bad Seed",num: "3", photo: "", description: ""},
            {id: "s11e4", title:"Baby",num: "4", photo: "", description: ""},
            {id: "s11e5", title:"Thin Lizzie",num: "5", photo: "", description: ""},
            {id: "s11e6", title:"Our Little World",num: "6", photo: "", description: ""},
            {id: "s11e7", title:"Plush",num: "7", photo: "", description: ""},
            {id: "s11e8", title:"Just My Imagination",num: "8", photo: "", description: ""},
            {id: "s11e9", title:"O Brother Where Art Thou?",num: "9", photo: "", description: ""},
            {id: "s11e10", title:"The Devil in the Details",num: "10", photo: "", description: ""},
            {id: "s11e11", title:"Into the Mystic",num: "11", photo: "", description: ""},
            {id: "s11e12", title:"Don't You Forget About Me",num: "12", photo: "", description: ""},
            {id: "s11e13", title:"Love Hurts",num: "13", photo: "", description: ""},
            {id: "s11e14", title:"The Vessel",num: "14", photo: "", description: ""},
            {id: "s11e15", title:"Beyond the Mat",num: "15", photo: "", description: ""},
            {id: "s11e16", title:"Safe House",num: "16", photo: "", description: ""},
            {id: "s11e17", title:"Red Meat",num: "17", photo: "", description: ""},
            {id: "s11e18", title:"Hell's Angel",num: "18", photo: "", description: ""},
            {id: "s11e19", title:"The Chitters",num: "19", photo: "", description: ""},
            {id: "s11e20", title:"Don't Call Me Shurley",num: "20", photo: "", description: ""},
            {id: "s11e21", title:"All in the Family",num: "21", photo: "", description: ""},
            {id: "s11e22", title:"We Happy Few",num: "22", photo: "", description: ""},
            {id: "s11e23", title:"Alpha and Omega ",num: "22", photo: "", description: ""},
        ]
    },
    {
        num:12,title: "Season Twelve", imgsrc:"/assets/seasons/season12.jpg", photo:"/assets/titlecards/s12.gif",
        description:"The British Men of Letters arrive in America, enforcing a ruthless approach to hunting. Meanwhile, Mary Winchester is resurrected and struggles to reconnect with her sons. The season focuses on family, legacy, and the cost of war. Lucifer returns and becomes a father, with his Nephilim child Jack becoming a key point of contention. The Winchesters face new enemies and painful sacrifices as alliances fracture.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2016", ratings:"7.9", bodyCount: "" , 
        epInfo: [
            {id: "s12e1", title:"Keep Calm and Carry On",num: "1", photo: "", description: ""},
            {id: "s12e2", title:"Mamma Mia",num: "2", photo: "", description: ""},
            {id: "s12e3", title:"The Foundry",num: "3", photo: "", description: ""},
            {id: "s12e4", title:"American Nightmare",num: "4", photo: "", description: ""},
            {id: "s12e5", title:"The One You've Been Waiting For",num: "5", photo: "", description: ""},
            {id: "s12e6", title:"Celebrating the Life of Asa Fox",num: "6", photo: "", description: ""},
            {id: "s12e7", title:"Rock Never Dies",num: "7", photo: "", description: ""},
            {id: "s12e8", title:"LOTUS",num: "8", photo: "", description: ""},
            {id: "s12e9", title:"First Blood",num: "9", photo: "", description: ""},
            {id: "s12e10",title:"Lily Sunder Has Some Regrets", num: "10", photo: "", description: ""},
            {id: "s12e11",title:"Regarding Dean", num: "11", photo: "", description: ""},
            {id: "s12e12",title:"Stuck in the Middle (With You)", num: "12", photo: "", description: ""},
            {id: "s12e13",title:"Family Feud", num: "13", photo: "", description: ""},
            {id: "s12e14",title:"The Raid", num: "14", photo: "", description: ""},
            {id: "s12e15",title:"Somewhere Between Heaven and Hell", num: "15", photo: "", description: ""},
            {id: "s12e16",title:"Ladies Drink Free", num: "16", photo: "", description: ""},
            {id: "s12e17",title:"The British Invasion", num: "17", photo: "", description: ""},
            {id: "s12e18",title:"The Memory Remains", num: "18", photo: "", description: ""},
            {id: "s12e19",title:"The Future", num: "19", photo: "", description: ""},
            {id: "s12e20",title:"Twigs & Twine & Tasha Banes", num: "20", photo: "", description: ""},
            {id: "s12e21",title:"There's Something About Mary", num: "21", photo: "", description: ""},
            {id: "s12e22",title:"Who We Are", num: "22", photo: "", description: ""},
            {id: "s12e23",title:"All Along the Watchtower", num: "22", photo: "", description: ""},
        ]
    },
    {
        num:13,title: "Season Thirteen", imgsrc:"/assets/seasons/season13.jpg", photo:"/assets/titlecards/s13.gif",
        description:"In the aftermath of Lucifer’s death and the birth of his son Jack, the brothers must guide the powerful Nephilim while navigating their grief over Castiel’s death. They discover an alternate universe where archangel Michael has conquered and seeks to invade their world. As Jack grows and grapples with his powers, the team faces tough choices to prevent another apocalypse. Alternate Michael becomes the season’s central antagonist.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2017", ratings:"7.8", bodyCount: "" , 
        epInfo: [
            {id: "s13e1", title:"Lost and Found",num: "1", photo: "", description: ""},
            {id: "s13e2", title:"The Rising Son",num: "2", photo: "", description: ""},
            {id: "s13e3", title:"Patience",num: "3", photo: "", description: ""},
            {id: "s13e4", title:"The Big Empty",num: "4", photo: "", description: ""},
            {id: "s13e5", title:"Advanced Thanatology",num: "5", photo: "", description: ""},
            {id: "s13e6", title:"Tombstone",num: "6", photo: "", description: ""},
            {id: "s13e7", title:"War of the Worlds",num: "7", photo: "", description: ""},
            {id: "s13e8", title:"The Scorpion and the Frog",num: "8", photo: "", description: ""},
            {id: "s13e9", title:"The Bad Place",num: "9", photo: "", description: ""},
            {id: "s13e10", title:"Wayward Sisters",num: "10", photo: "", description: ""},
            {id: "s13e11", title:"Breakdown",num: "11", photo: "", description: ""},
            {id: "s13e12", title:"Various & Sundry Villains",num: "12", photo: "", description: ""},
            {id: "s13e13", title:"Devil's Bargain",num: "13", photo: "", description: ""},
            {id: "s13e14", title:"Good Intentions",num: "14", photo: "", description: ""},
            {id: "s13e15", title:"A Most Holy Man",num: "15", photo: "", description: ""},
            {id: "s13e16", title:"ScoobyNatural",num: "16", photo: "", description: ""},
            {id: "s13e17", title:"The Thing",num: "17", photo: "", description: ""},
            {id: "s13e18", title:"Bring 'Em Back Alive",num: "18", photo: "", description: ""},
            {id: "s13e19", title:"Funeralla",num: "19", photo: "", description: ""},
            {id: "s13e20", title:"Unfinished Business",num: "20", photo: "", description: ""},
            {id: "s13e21", title:"Beat the Devil",num: "21", photo: "", description: ""},
            {id: "s13e22", title:"Exodus",num: "22", photo: "", description: ""},
            {id: "s13e23", title:"Let the Good Times Roll",num: "22", photo: "", description: ""},
        ]
    },
    {
        num:14,title: "Season Fourteen", imgsrc:"/assets/seasons/season14.jpg", photo:"/assets/titlecards/s14.gif",
        description:"Michael from the alternate universe possesses Dean and launches a campaign to create a monstrous army. Jack loses his powers and later sacrifices his soul to regain them. As tensions rise and Jack’s morality falters, the lines between good and evil blur. Chuck (God) reemerges, revealing himself as a manipulative creator who sees the Winchesters’ lives as entertainment. The season ends with Chuck turning against the brothers, unleashing Hell on Earth.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "20", yearAired: "2018", ratings:"7.5", bodyCount: "" , 
        epInfo: [
            {id: "s14e1", title:"Stranger in a Strange Land",num: "1", photo: "", description: ""},
            {id: "s14e2", title:"Gods and Monsters",num: "2", photo: "", description: ""},
            {id: "s14e3", title:"The Scar",num: "3", photo: "", description: ""},
            {id: "s14e4", title:"Mint Condition",num: "4", photo: "", description: ""},
            {id: "s14e5", title:"Nightmare Logic",num: "5", photo: "", description: ""},
            {id: "s14e6", title:"Optimism",num: "6", photo: "", description: ""},
            {id: "s14e7", title:"Unhuman Nature",num: "7", photo: "", description: ""},
            {id: "s14e8", title:"Byzantium",num: "8", photo: "", description: ""},
            {id: "s14e9", title:"The Spear",num: "9", photo: "", description: ""},
            {id: "s14e10", title:"Nihilism",num: "10", photo: "", description: ""},
            {id: "s14e11", title:"Damaged Goods",num: "11", photo: "", description: ""},
            {id: "s14e12", title:"Prophet and Loss",num: "12", photo: "", description: ""},
            {id: "s14e13", title:"Lebanon",num: "13", photo: "", description: ""},
            {id: "s14e14", title:"Ouroboros",num: "14", photo: "", description: ""},
            {id: "s14e15", title:"Peace of Mind",num: "15", photo: "", description: ""},
            {id: "s14e16", title:"Don't Go in the Woods",num: "16", photo: "", description: ""},
            {id: "s14e17", title:"Game Night",num: "17", photo: "", description: ""},
            {id: "s14e18", title:"Absence",num: "18", photo: "", description: ""},
            {id: "s14e19", title:"Jack in the Box",num: "19", photo: "", description: ""},
            {id: "s14e20", title:"Moriah",num: "20", photo: "", description: ""},
        ]

    },
    {
        num:15,title: "Season Fifteen", imgsrc:"/assets/seasons/season15.jpg", photo:"/assets/titlecards/s15.gif",
        description:"The final season pits Sam and Dean against God himself, who aims to destroy all alternate realities and start fresh. The brothers face an army of the dead, old enemies, and cosmic uncertainty. As they search for a way to defeat Chuck, they’re forced to question fate and free will. Jack ultimately becomes the new God, restoring balance. Dean sacrifices his life in a final hunt, and Sam lives out a long life before reuniting with Dean in the afterlif", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "20", yearAired: "2019", ratings:"7.4", bodyCount: "" , 
        eepInfo: [
            {id: "s15e1", title:"Back to the Future",num: "1", photo: "", description: ""},
            {id: "s15e2", title:"Raising Hell",num: "2", photo: "", description: ""},
            {id: "s15e3", title:"The Rupture",num: "3", photo: "", description: ""},
            {id: "s15e4", title:"Atomic Monsters",num: "4", photo: "", description: ""},
            {id: "s15e5", title:"Proverbs 17:3",num: "5", photo: "", description: ""},
            {id: "s15e6", title:"Golden Time",num: "6", photo: "", description: ""},
            {id: "s15e7", title:"Last Call",num: "7", photo: "", description: ""},
            {id: "s15e8", title:"Our Father, Who Aren't in Heaven",num: "8", photo: "", description: ""},
            {id: "s15e9", title:"The Trap",num: "9", photo: "", description: ""},
            {id: "s15e10", title:"The Heroes' Journey",num: "10", photo: "", description: ""},
            {id: "s15e11", title:"The Gamblers",num: "11", photo: "", description: ""},
            {id: "s15e12", title:"Galaxy Brain",num: "12", photo: "", description: ""},
            {id: "s15e13", title:"Destiny's Child",num: "13", photo: "", description: ""},
            {id: "s15e14", title:"Last Holiday",num: "14", photo: "", description: ""},
            {id: "s15e15", title:"Gimme Shelter",num: "15", photo: "", description: ""},
            {id: "s15e16", title:"Drag Me Away (From You)",num: "16", photo: "", description: ""},
            {id: "s15e17", title:"Unity",num: "17", photo: "", description: ""},
            {id: "s15e18", title:"Despair",num: "18", photo: "", description: ""},
            {id: "s15e19", title:"Inherit the Earth",num: "19", photo: "", description: ""},
            {id: "s15e20", title:"Carry On",num: "20", photo: "", description: ""},
        ]

    }
]