//takes title, imgsrc, description, majorUpdates, characterIntros, epNumbers, yearAired, ratings, bodyCount
export const episodes = [
    //Season One:
    {
        num:1, title: "Season One", imgsrc:"/assets/seasons/season1.jpg", photo:"/assets/titlecards/s1.gif", 
        description:"Brothers Sam and Dean Winchester reunite after years apart when their father goes missing during a hunting trip. As they travel across the country battling urban legends and supernatural creatures, they uncover clues about their family’s tragic past and the demon responsible for their mother’s death. The main conflict revolves around locating their father and confronting the Yellow-Eyed Demon, Azazel, who is revealed to be connected to a sinister plan involving Sam.", 
        majorUpdates: [{id: "dean", name:"Dean Winchester", text:"Critically injured in a car accident "}], 
        characterIntros: [{id:"dean", name:"Dean Winchester",text:"A loyal, battle-ready hunter searching for their missing father."}, {id:"sam", name:"Sam Winchester",text:"A reluctant hunter drawn back in after his girlfriend’s death."}, {id:"john", name:"John Winchester",text:"A missing hunter whose quest for revenge drives the story."}, ], 
        epNumbers: "22", yearAired: "2005", ratings:"8.5", bodyCount: "" , 
        epInfo: [
            {id: "s1e1", num: "1", photo: "", description: ""},
            {id: "s1e2", num: "2", photo: "", description: ""},
            {id: "s1e3", num: "3", photo: "", description: ""},
            {id: "s1e4", num: "4", photo: "", description: ""},
            {id: "s1e5", num: "5", photo: "", description: ""},
            {id: "s1e6", num: "6", photo: "", description: ""},
            {id: "s1e7", num: "7", photo: "", description: ""},
            {id: "s1e8", num: "8", photo: "", description: ""},
            {id: "s1e9", num: "9", photo: "", description: ""},
            {id: "s1e10", num: "10", photo: "", description: ""},
            {id: "s1e11", num: "11", photo: "", description: ""},
            {id: "s1e12", num: "12", photo: "", description: ""},
            {id: "s1e13", num: "13", photo: "", description: ""},
            {id: "s1e14", num: "14", photo: "", description: ""},
            {id: "s1e15", num: "15", photo: "", description: ""},
            {id: "s1e16", num: "16", photo: "", description: ""},
            {id: "s1e17", num: "17", photo: "", description: ""},
            {id: "s1e18", num: "18", photo: "", description: ""},
            {id: "s1e19", num: "19", photo: "", description: ""},
            {id: "s1e20", num: "20", photo: "", description: ""},
            {id: "s1e21", num: "21", photo: "", description: ""},
            {id: "s1e22", num: "22", photo: "", description: ""}
        ]

    },
    {
        num:2,title: "Season Two", imgsrc:"/assets/seasons/season2.jpg", photo:"/assets/titlecards/s2.gif",
        description:"Following their father’s death and the revelation of Azazel’s plans, Sam and Dean continue hunting while struggling with the emotional fallout. Sam begins to exhibit strange powers, and they encounter others like him—children with psychic abilities also targeted by Azazel. As the brothers try to stop a demonic war from unfolding, they face the loss of friends and family. Azazel remains the key antagonist, orchestrating a deadly contest that pits the special children against each other.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2006", ratings:"8.6", bodyCount: "" , 
        epInfo: [
            {id: "s2e1", num: "1", photo: "", description: ""},
            {id: "s2e2", num: "2", photo: "", description: ""},
            {id: "s2e3", num: "3", photo: "", description: ""},
            {id: "s2e4", num: "4", photo: "", description: ""},
            {id: "s2e5", num: "5", photo: "", description: ""},
            {id: "s2e6", num: "6", photo: "", description: ""},
            {id: "s2e7", num: "7", photo: "", description: ""},
            {id: "s2e8", num: "8", photo: "", description: ""},
            {id: "s2e9", num: "9", photo: "", description: ""},
            {id: "s2e10", num: "10", photo: "", description: ""},
            {id: "s2e11", num: "11", photo: "", description: ""},
            {id: "s2e12", num: "12", photo: "", description: ""},
            {id: "s2e13", num: "13", photo: "", description: ""},
            {id: "s2e14", num: "14", photo: "", description: ""},
            {id: "s2e15", num: "15", photo: "", description: ""},
            {id: "s2e16", num: "16", photo: "", description: ""},
            {id: "s2e17", num: "17", photo: "", description: ""},
            {id: "s2e18", num: "18", photo: "", description: ""},
            {id: "s2e19", num: "19", photo: "", description: ""},
            {id: "s2e20", num: "20", photo: "", description: ""},
            {id: "s2e21", num: "21", photo: "", description: ""},
            {id: "s2e22", num: "22", photo: "", description: ""}
        ]

    },
    {
        num:3,title: "Season Three", imgsrc:"/assets/seasons/season3.jpg", photo:"/assets/titlecards/s3.gif",
        description:"After making a deal with a crossroads demon to save Sam’s life, Dean has one year left to live before going to Hell. The brothers desperately search for a way to break the contract. Their quest is made harder by the rise of new threats, including demons freed from Hell by Azazel’s death. Among these is Lilith, a powerful demon who holds Dean’s contract and is systematically eliminating psychic children like Sam.",
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "16", yearAired: "2007", ratings:"8.4", bodyCount: "" , 
        epInfo: [
            {id: "s3e1", num: "1", photo: "", description: ""},
            {id: "s3e2", num: "2", photo: "", description: ""},
            {id: "s3e3", num: "3", photo: "", description: ""},
            {id: "s3e4", num: "4", photo: "", description: ""},
            {id: "s3e5", num: "5", photo: "", description: ""},
            {id: "s3e6", num: "6", photo: "", description: ""},
            {id: "s3e7", num: "7", photo: "", description: ""},
            {id: "s3e8", num: "8", photo: "", description: ""},
            {id: "s3e9", num: "9", photo: "", description: ""},
            {id: "s3e10", num: "10", photo: "", description: ""},
            {id: "s3e11", num: "11", photo: "", description: ""},
            {id: "s3e12", num: "12", photo: "", description: ""},
            {id: "s3e13", num: "13", photo: "", description: ""},
            {id: "s3e14", num: "14", photo: "", description: ""},
            {id: "s3e15", num: "15", photo: "", description: ""},
            {id: "s3e16", num: "16", photo: "", description: ""},
        ]

    },
    {
        num:4,title: "Season Four", imgsrc:"/assets/seasons/season4.jpg", photo:"/assets/titlecards/s4.gif",
        description:"Dean is miraculously saved from Hell by Castiel, an angel who brings word of an impending apocalypse. Heaven and Hell wage war on Earth, using humanity as pawns. As Sam becomes addicted to demon blood and aligns with a demon named Ruby, the brothers’ trust fractures. The season builds to a devastating finale in which Lilith’s death—at Sam’s hands—releases Lucifer from his prison, setting the stage for the apocalypse.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2008", ratings:"8.5", bodyCount: "" , 
        epInfo: [
            {id: "s4e1", num: "1", photo: "", description: ""},
            {id: "s4e2", num: "2", photo: "", description: ""},
            {id: "s4e3", num: "3", photo: "", description: ""},
            {id: "s4e4", num: "4", photo: "", description: ""},
            {id: "s4e5", num: "5", photo: "", description: ""},
            {id: "s4e6", num: "6", photo: "", description: ""},
            {id: "s4e7", num: "7", photo: "", description: ""},
            {id: "s4e8", num: "8", photo: "", description: ""},
            {id: "s4e9", num: "9", photo: "", description: ""},
            {id: "s4e10", num: "10", photo: "", description: ""},
            {id: "s4e11", num: "11", photo: "", description: ""},
            {id: "s4e12", num: "12", photo: "", description: ""},
            {id: "s4e13", num: "13", photo: "", description: ""},
            {id: "s4e14", num: "14", photo: "", description: ""},
            {id: "s4e15", num: "15", photo: "", description: ""},
            {id: "s4e16", num: "16", photo: "", description: ""},
            {id: "s4e17", num: "17", photo: "", description: ""},
            {id: "s4e18", num: "18", photo: "", description: ""},
            {id: "s4e19", num: "19", photo: "", description: ""},
            {id: "s4e20", num: "20", photo: "", description: ""},
            {id: "s4e21", num: "21", photo: "", description: ""},
            {id: "s4e22", num: "22", photo: "", description: ""}
        ]

    },
    {
        num:5,title: "Season Five", imgsrc:"/assets/seasons/season5.jpg", photo:"/assets/titlecards/s5.gif",
        description:"Lucifer is free, and the apocalypse is in full swing. Sam and Dean learn they are destined to become vessels for Lucifer and Michael in a final, world-ending showdown. While resisting fate, they search for a way to trap Lucifer again, eventually using the Four Horsemen’s rings to open the cage. With sacrificial courage, Sam takes Lucifer back into the cage, ending the apocalypse. Lucifer is the main antagonist, driving the conflict between destiny and free will.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2009", ratings:"8.8", bodyCount: "" , 
        epInfo: [
            {id: "s5e1", num: "1", photo: "", description: ""},
            {id: "s5e2", num: "2", photo: "", description: ""},
            {id: "s5e3", num: "3", photo: "", description: ""},
            {id: "s5e4", num: "4", photo: "", description: ""},
            {id: "s5e5", num: "5", photo: "", description: ""},
            {id: "s5e6", num: "6", photo: "", description: ""},
            {id: "s5e7", num: "7", photo: "", description: ""},
            {id: "s5e8", num: "8", photo: "", description: ""},
            {id: "s5e9", num: "9", photo: "", description: ""},
            {id: "s5e10", num: "10", photo: "", description: ""},
            {id: "s5e11", num: "11", photo: "", description: ""},
            {id: "s5e12", num: "12", photo: "", description: ""},
            {id: "s5e13", num: "13", photo: "", description: ""},
            {id: "s5e14", num: "14", photo: "", description: ""},
            {id: "s5e15", num: "15", photo: "", description: ""},
            {id: "s5e16", num: "16", photo: "", description: ""},
            {id: "s5e17", num: "17", photo: "", description: ""},
            {id: "s5e18", num: "18", photo: "", description: ""},
            {id: "s5e19", num: "19", photo: "", description: ""},
            {id: "s5e20", num: "20", photo: "", description: ""},
            {id: "s5e21", num: "21", photo: "", description: ""},
            {id: "s5e22", num: "22", photo: "", description: ""}
        ]

    },
    {
        num:6,title: "Season Six", imgsrc:"/assets/seasons/season6.jpg", photo:"/assets/titlecards/s6.gif",
        description:"The aftermath of the apocalypse leaves the supernatural world in chaos. Sam returns mysteriously from Hell—soulless and emotionally void. Dean, trying to settle into normal life, is pulled back into hunting as new threats emerge, including creatures created by Eve, the Mother of All Monsters. As they face increasingly strange beings, the brothers uncover a plot involving the souls of Purgatory, manipulated by Castiel in his quest to stop Raphael’s plans for another apocalypse.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "22", yearAired: "2010", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s6e1", num: "1", photo: "", description: ""},
            {id: "s6e2", num: "2", photo: "", description: ""},
            {id: "s6e3", num: "3", photo: "", description: ""},
            {id: "s6e4", num: "4", photo: "", description: ""},
            {id: "s6e5", num: "5", photo: "", description: ""},
            {id: "s6e6", num: "6", photo: "", description: ""},
            {id: "s6e7", num: "7", photo: "", description: ""},
            {id: "s6e8", num: "8", photo: "", description: ""},
            {id: "s6e9", num: "9", photo: "", description: ""},
            {id: "s6e10", num: "10", photo: "", description: ""},
            {id: "s6e11", num: "11", photo: "", description: ""},
            {id: "s6e12", num: "12", photo: "", description: ""},
            {id: "s6e13", num: "13", photo: "", description: ""},
            {id: "s6e14", num: "14", photo: "", description: ""},
            {id: "s6e15", num: "15", photo: "", description: ""},
            {id: "s6e16", num: "16", photo: "", description: ""},
            {id: "s6e17", num: "17", photo: "", description: ""},
            {id: "s6e18", num: "18", photo: "", description: ""},
            {id: "s6e19", num: "19", photo: "", description: ""},
            {id: "s6e20", num: "20", photo: "", description: ""},
            {id: "s6e21", num: "21", photo: "", description: ""},
            {id: "s6e22", num: "22", photo: "", description: ""}
        ]

    },
    {
        num:7,title: "Season Seven", imgsrc:"/assets/seasons/season7.jpg", photo:"/assets/titlecards/s7.gif",
        description:"The Leviathans, ancient creatures predating angels and demons, escape from Purgatory and begin taking over human society. Led by the cunning Dick Roman, they aim to turn humanity into complacent, edible cattle. As Sam suffers hallucinations and Dean spirals into despair, the brothers struggle to find a way to stop beings that can’t be killed by conventional means. The Leviathans become the most difficult and alien threat they’ve faced yet.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2011", ratings:"8.0", bodyCount: "" , 
        epInfo: [
            {id: "s7e1", num: "1", photo: "", description: ""},
            {id: "s7e2", num: "2", photo: "", description: ""},
            {id: "s7e3", num: "3", photo: "", description: ""},
            {id: "s7e4", num: "4", photo: "", description: ""},
            {id: "s7e5", num: "5", photo: "", description: ""},
            {id: "s7e6", num: "6", photo: "", description: ""},
            {id: "s7e7", num: "7", photo: "", description: ""},
            {id: "s7e8", num: "8", photo: "", description: ""},
            {id: "s7e9", num: "9", photo: "", description: ""},
            {id: "s7e10", num: "10", photo: "", description: ""},
            {id: "s7e11", num: "11", photo: "", description: ""},
            {id: "s7e12", num: "12", photo: "", description: ""},
            {id: "s7e13", num: "13", photo: "", description: ""},
            {id: "s7e14", num: "14", photo: "", description: ""},
            {id: "s7e15", num: "15", photo: "", description: ""},
            {id: "s7e16", num: "16", photo: "", description: ""},
            {id: "s7e17", num: "17", photo: "", description: ""},
            {id: "s7e18", num: "18", photo: "", description: ""},
            {id: "s7e19", num: "19", photo: "", description: ""},
            {id: "s7e20", num: "20", photo: "", description: ""},
            {id: "s7e21", num: "21", photo: "", description: ""},
            {id: "s7e22", num: "22", photo: "", description: ""},
            {id: "s7e23", num: "23", photo:"", description: ""}
        ]

    },
    {
        num:8,title: "Season Eight", imgsrc:"/assets/seasons/season8.jpg", photo:"/assets/titlecards/s8.gif",
        description:"After being trapped in Purgatory, Dean returns with a vampire ally, while Sam has tried to live a normal life. The brothers reunite to search for the Men of Letters' legacy, which leads them to the trials needed to close the gates of Hell permanently. As Sam completes each trial, it takes a physical toll on him. The season focuses on trust, sacrifice, and the brothers’ evolving roles. Abaddon, a resurrected Knight of Hell, emerges as a significant threat.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2012", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s8e1", num: "1", photo: "", description: ""},
            {id: "s8e2", num: "2", photo: "", description: ""},
            {id: "s8e3", num: "3", photo: "", description: ""},
            {id: "s8e4", num: "4", photo: "", description: ""},
            {id: "s8e5", num: "5", photo: "", description: ""},
            {id: "s8e6", num: "6", photo: "", description: ""},
            {id: "s8e7", num: "7", photo: "", description: ""},
            {id: "s8e8", num: "8", photo: "", description: ""},
            {id: "s8e9", num: "9", photo: "", description: ""},
            {id: "s8e10", num: "10", photo: "", description: ""},
            {id: "s8e11", num: "11", photo: "", description: ""},
            {id: "s8e12", num: "12", photo: "", description: ""},
            {id: "s8e13", num: "13", photo: "", description: ""},
            {id: "s8e14", num: "14", photo: "", description: ""},
            {id: "s8e15", num: "15", photo: "", description: ""},
            {id: "s8e16", num: "16", photo: "", description: ""},
            {id: "s8e17", num: "17", photo: "", description: ""},
            {id: "s8e18", num: "18", photo: "", description: ""},
            {id: "s8e19", num: "19", photo: "", description: ""},
            {id: "s8e20", num: "20", photo: "", description: ""},
            {id: "s8e21", num: "21", photo: "", description: ""},
            {id: "s8e22", num: "22", photo: "", description: ""},
            {id: "s8e23", num:"23", photo:"", description:""}
        ]

    },
    {
        num:9,title: "Season Nine", imgsrc:"/assets/seasons/season9.jpg", photo:"/assets/titlecards/s9.gif",
        description:"With the gates of Heaven closed and angels cast out, chaos reigns. Dean, desperate to save a dying Sam, allows an angel named Gadreel to possess him, straining their relationship. Meanwhile, the Mark of Cain gives Dean incredible power at a cost. Metatron, Heaven’s former scribe, manipulates events to gain power and declare himself the new God. The season ends with Dean dying and resurrecting as a demon, thanks to the Mark.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2013", ratings:"8.0", bodyCount: "" , 
        epInfo: [
            {id: "s9e1", num: "1", photo: "", description: ""},
            {id: "s9e2", num: "2", photo: "", description: ""},
            {id: "s9e3", num: "3", photo: "", description: ""},
            {id: "s9e4", num: "4", photo: "", description: ""},
            {id: "s9e5", num: "5", photo: "", description: ""},
            {id: "s9e6", num: "6", photo: "", description: ""},
            {id: "s9e7", num: "7", photo: "", description: ""},
            {id: "s9e8", num: "8", photo: "", description: ""},
            {id: "s9e9", num: "9", photo: "", description: ""},
            {id: "s9e10", num: "10", photo: "", description: ""},
            {id: "s9e11", num: "11", photo: "", description: ""},
            {id: "s9e12", num: "12", photo: "", description: ""},
            {id: "s9e13", num: "13", photo: "", description: ""},
            {id: "s9e14", num: "14", photo: "", description: ""},
            {id: "s9e15", num: "15", photo: "", description: ""},
            {id: "s9e16", num: "16", photo: "", description: ""},
            {id: "s9e17", num: "17", photo: "", description: ""},
            {id: "s9e18", num: "18", photo: "", description: ""},
            {id: "s9e19", num: "19", photo: "", description: ""},
            {id: "s9e20", num: "20", photo: "", description: ""},
            {id: "s9e21", num: "21", photo: "", description: ""},
            {id: "s9e22", num: "22", photo: "", description: ""},
            {id: "s9e22", num: "22", photo: "", description: ""},
        ]

    },
    {
        num:10,title: "Season Ten", imgsrc:"/assets/seasons/season10.jpg", photo:"/assets/titlecards/s10.gif",
        description:"Dean battles the effects of the Mark of Cain, which turns him increasingly violent. Sam searches for a cure while Castiel deals with dwindling grace. Crowley’s alliances shift as the brothers clash with Rowena, a powerful witch and Crowley’s mother. The Mark’s true origin is revealed to be tied to an ancient entity called the Darkness. Removing the Mark unleashes this being, setting up an even more powerful adversary.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2014", ratings:"8.2", bodyCount: "" , 
        epInfo: [
            {id: "s10e1", num: "1", photo: "", description: ""},
            {id: "s10e2", num: "2", photo: "", description: ""},
            {id: "s10e3", num: "3", photo: "", description: ""},
            {id: "s10e4", num: "4", photo: "", description: ""},
            {id: "s10e5", num: "5", photo: "", description: ""},
            {id: "s10e6", num: "6", photo: "", description: ""},
            {id: "s10e7", num: "7", photo: "", description: ""},
            {id: "s10e8", num: "8", photo: "", description: ""},
            {id: "s10e9", num: "9", photo: "", description: ""},
            {id: "s10e10", num: "10", photo: "", description: ""},
            {id: "s10e11", num: "11", photo: "", description: ""},
            {id: "s10e12", num: "12", photo: "", description: ""},
            {id: "s10e13", num: "13", photo: "", description: ""},
            {id: "s10e14", num: "14", photo: "", description: ""},
            {id: "s10e15", num: "15", photo: "", description: ""},
            {id: "s10e16", num: "16", photo: "", description: ""},
            {id: "s10e17", num: "17", photo: "", description: ""},
            {id: "s10e18", num: "18", photo: "", description: ""},
            {id: "s10e19", num: "19", photo: "", description: ""},
            {id: "s10e20", num: "20", photo: "", description: ""},
            {id: "s10e21", num: "21", photo: "", description: ""},
            {id: "s10e22", num: "22", photo: "", description: ""},
            {id: "s10e23", num: "22", photo: "", description: ""},
        ]
    },
    {
        num:11,title: "Season Eleven", imgsrc:"/assets/seasons/season11.jpg", photo:"/assets/titlecards/s11.gif",
        description:"The Darkness, now known as Amara, emerges and threatens to destroy the universe. She is God’s sister and seeks revenge for her imprisonment. As Amara grows in power, even angels and demons prove powerless. The Winchesters attempt to find God—revealed to be Chuck Shurley—and convince him to help. The season becomes a cosmic family drama between Chuck and Amara, leading to a fragile truce that restores balance to the universe.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2015", ratings:"8.3", bodyCount: "" , 
        epInfo: [
            {id: "s11e1", num: "1", photo: "", description: ""},
            {id: "s11e2", num: "2", photo: "", description: ""},
            {id: "s11e3", num: "3", photo: "", description: ""},
            {id: "s11e4", num: "4", photo: "", description: ""},
            {id: "s11e5", num: "5", photo: "", description: ""},
            {id: "s11e6", num: "6", photo: "", description: ""},
            {id: "s11e7", num: "7", photo: "", description: ""},
            {id: "s11e8", num: "8", photo: "", description: ""},
            {id: "s11e9", num: "9", photo: "", description: ""},
            {id: "s11e10", num: "10", photo: "", description: ""},
            {id: "s11e11", num: "11", photo: "", description: ""},
            {id: "s11e12", num: "12", photo: "", description: ""},
            {id: "s11e13", num: "13", photo: "", description: ""},
            {id: "s11e14", num: "14", photo: "", description: ""},
            {id: "s11e15", num: "15", photo: "", description: ""},
            {id: "s11e16", num: "16", photo: "", description: ""},
            {id: "s11e17", num: "17", photo: "", description: ""},
            {id: "s11e18", num: "18", photo: "", description: ""},
            {id: "s11e19", num: "19", photo: "", description: ""},
            {id: "s11e20", num: "20", photo: "", description: ""},
            {id: "s11e21", num: "21", photo: "", description: ""},
            {id: "s11e22", num: "22", photo: "", description: ""},
            {id: "s11e23", num: "22", photo: "", description: ""},
        ]
    },
    {
        num:12,title: "Season Twelve", imgsrc:"/assets/seasons/season12.jpg", photo:"/assets/titlecards/s12.gif",
        description:"The British Men of Letters arrive in America, enforcing a ruthless approach to hunting. Meanwhile, Mary Winchester is resurrected and struggles to reconnect with her sons. The season focuses on family, legacy, and the cost of war. Lucifer returns and becomes a father, with his Nephilim child Jack becoming a key point of contention. The Winchesters face new enemies and painful sacrifices as alliances fracture.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2016", ratings:"7.9", bodyCount: "" , 
        epInfo: [
            {id: "s12e1", num: "1", photo: "", description: ""},
            {id: "s12e2", num: "2", photo: "", description: ""},
            {id: "s12e3", num: "3", photo: "", description: ""},
            {id: "s12e4", num: "4", photo: "", description: ""},
            {id: "s12e5", num: "5", photo: "", description: ""},
            {id: "s12e6", num: "6", photo: "", description: ""},
            {id: "s12e7", num: "7", photo: "", description: ""},
            {id: "s12e8", num: "8", photo: "", description: ""},
            {id: "s12e9", num: "9", photo: "", description: ""},
            {id: "s12e10", num: "10", photo: "", description: ""},
            {id: "s12e11", num: "11", photo: "", description: ""},
            {id: "s12e12", num: "12", photo: "", description: ""},
            {id: "s12e13", num: "13", photo: "", description: ""},
            {id: "s12e14", num: "14", photo: "", description: ""},
            {id: "s12e15", num: "15", photo: "", description: ""},
            {id: "s12e16", num: "16", photo: "", description: ""},
            {id: "s12e17", num: "17", photo: "", description: ""},
            {id: "s12e18", num: "18", photo: "", description: ""},
            {id: "s12e19", num: "19", photo: "", description: ""},
            {id: "s12e20", num: "20", photo: "", description: ""},
            {id: "s12e21", num: "21", photo: "", description: ""},
            {id: "s12e22", num: "22", photo: "", description: ""},
            {id: "s12e23", num: "22", photo: "", description: ""},
        ]
    },
    {
        num:13,title: "Season Thirteen", imgsrc:"/assets/seasons/season13.jpg", photo:"/assets/titlecards/s13.gif",
        description:"In the aftermath of Lucifer’s death and the birth of his son Jack, the brothers must guide the powerful Nephilim while navigating their grief over Castiel’s death. They discover an alternate universe where archangel Michael has conquered and seeks to invade their world. As Jack grows and grapples with his powers, the team faces tough choices to prevent another apocalypse. Alternate Michael becomes the season’s central antagonist.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "23", yearAired: "2017", ratings:"7.8", bodyCount: "" , 
        epInfo: [
            {id: "s13e1", num: "1", photo: "", description: ""},
            {id: "s13e2", num: "2", photo: "", description: ""},
            {id: "s13e3", num: "3", photo: "", description: ""},
            {id: "s13e4", num: "4", photo: "", description: ""},
            {id: "s13e5", num: "5", photo: "", description: ""},
            {id: "s13e6", num: "6", photo: "", description: ""},
            {id: "s13e7", num: "7", photo: "", description: ""},
            {id: "s13e8", num: "8", photo: "", description: ""},
            {id: "s13e9", num: "9", photo: "", description: ""},
            {id: "s13e10", num: "10", photo: "", description: ""},
            {id: "s13e11", num: "11", photo: "", description: ""},
            {id: "s13e12", num: "12", photo: "", description: ""},
            {id: "s13e13", num: "13", photo: "", description: ""},
            {id: "s13e14", num: "14", photo: "", description: ""},
            {id: "s13e15", num: "15", photo: "", description: ""},
            {id: "s13e16", num: "16", photo: "", description: ""},
            {id: "s13e17", num: "17", photo: "", description: ""},
            {id: "s13e18", num: "18", photo: "", description: ""},
            {id: "s13e19", num: "19", photo: "", description: ""},
            {id: "s13e20", num: "20", photo: "", description: ""},
            {id: "s13e21", num: "21", photo: "", description: ""},
            {id: "s13e22", num: "22", photo: "", description: ""},
            {id: "s13e23", num: "22", photo: "", description: ""},
        ]
    },
    {
        num:14,title: "Season Fourteen", imgsrc:"/assets/seasons/season14.jpg", photo:"/assets/titlecards/s14.gif",
        description:"Michael from the alternate universe possesses Dean and launches a campaign to create a monstrous army. Jack loses his powers and later sacrifices his soul to regain them. As tensions rise and Jack’s morality falters, the lines between good and evil blur. Chuck (God) reemerges, revealing himself as a manipulative creator who sees the Winchesters’ lives as entertainment. The season ends with Chuck turning against the brothers, unleashing Hell on Earth.", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "20", yearAired: "2018", ratings:"7.5", bodyCount: "" , 
        epInfo: [
            {id: "s14e1", num: "1", photo: "", description: ""},
            {id: "s14e2", num: "2", photo: "", description: ""},
            {id: "s14e3", num: "3", photo: "", description: ""},
            {id: "s14e4", num: "4", photo: "", description: ""},
            {id: "s14e5", num: "5", photo: "", description: ""},
            {id: "s14e6", num: "6", photo: "", description: ""},
            {id: "s14e7", num: "7", photo: "", description: ""},
            {id: "s14e8", num: "8", photo: "", description: ""},
            {id: "s14e9", num: "9", photo: "", description: ""},
            {id: "s14e10", num: "10", photo: "", description: ""},
            {id: "s14e11", num: "11", photo: "", description: ""},
            {id: "s14e12", num: "12", photo: "", description: ""},
            {id: "s14e13", num: "13", photo: "", description: ""},
            {id: "s14e14", num: "14", photo: "", description: ""},
            {id: "s14e15", num: "15", photo: "", description: ""},
            {id: "s14e16", num: "16", photo: "", description: ""},
            {id: "s14e17", num: "17", photo: "", description: ""},
            {id: "s14e18", num: "18", photo: "", description: ""},
            {id: "s14e19", num: "19", photo: "", description: ""},
            {id: "s14e20", num: "20", photo: "", description: ""},
        ]

    },
    {
        num:15,title: "Season Fifteen", imgsrc:"/assets/seasons/season15.jpg", photo:"/assets/titlecards/s15.gif",
        description:"The final season pits Sam and Dean against God himself, who aims to destroy all alternate realities and start fresh. The brothers face an army of the dead, old enemies, and cosmic uncertainty. As they search for a way to defeat Chuck, they’re forced to question fate and free will. Jack ultimately becomes the new God, restoring balance. Dean sacrifices his life in a final hunt, and Sam lives out a long life before reuniting with Dean in the afterlif", 
        majorUpdates: [{id:"", name:"", text:""}], 
        characterIntros: [{id:"", name:"",text:""}], epNumbers: "20", yearAired: "2019", ratings:"7.4", bodyCount: "" , 
        eepInfo: [
            {id: "s15e1", num: "1", photo: "", description: ""},
            {id: "s15e2", num: "2", photo: "", description: ""},
            {id: "s15e3", num: "3", photo: "", description: ""},
            {id: "s15e4", num: "4", photo: "", description: ""},
            {id: "s15e5", num: "5", photo: "", description: ""},
            {id: "s15e6", num: "6", photo: "", description: ""},
            {id: "s15e7", num: "7", photo: "", description: ""},
            {id: "s15e8", num: "8", photo: "", description: ""},
            {id: "s15e9", num: "9", photo: "", description: ""},
            {id: "s15e10", num: "10", photo: "", description: ""},
            {id: "s15e11", num: "11", photo: "", description: ""},
            {id: "s15e12", num: "12", photo: "", description: ""},
            {id: "s15e13", num: "13", photo: "", description: ""},
            {id: "s15e14", num: "14", photo: "", description: ""},
            {id: "s15e15", num: "15", photo: "", description: ""},
            {id: "s15e16", num: "16", photo: "", description: ""},
            {id: "s15e17", num: "17", photo: "", description: ""},
            {id: "s15e18", num: "18", photo: "", description: ""},
            {id: "s15e19", num: "19", photo: "", description: ""},
            {id: "s15e20", num: "20", photo: "", description: ""},
        ]

    }
]