//takes title, imgsrc, description, majorUpdates, characterIntros, epNumbers, yearAired, totalMonsters, bodyCount
export const episodes = [
    //Season One:
    {num:1, title: "Season One", imgsrc:"/assets/seasons/season1.jpg", photo:"/assets/titlecards/s1.gif", description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:2,title: "Season Two", imgsrc:"/assets/seasons/season2.jpg", photo:"/assets/titlecards/s2.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:3,title: "Season Three", imgsrc:"/assets/seasons/season3.jpg", photo:"/assets/titlecards/s3.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:4,title: "Season Four", imgsrc:"/assets/seasons/season4.jpg", photo:"/assets/titlecards/s4.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:5,title: "Season Five", imgsrc:"/assets/seasons/season5.jpg", photo:"/assets/titlecards/s5.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:6,title: "Season Six", imgsrc:"/assets/seasons/season6.jpg", photo:"/assets/titlecards/s6.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:7,title: "Season Seven", imgsrc:"/assets/seasons/season7.jpg", photo:"/assets/titlecards/s7.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:8,title: "Season Eight", imgsrc:"/assets/seasons/season8.jpg", photo:"/assets/titlecards/s8.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:9,title: "Season Nine", imgsrc:"/assets/seasons/season9.jpg", photo:"/assets/titlecards/s9.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:10,title: "Season Ten", imgsrc:"/assets/seasons/season10.jpg", photo:"/assets/titlecards/s10.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:11,title: "Season Eleven", imgsrc:"/assets/seasons/season11.jpg", photo:"/assets/titlecards/s11.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:12,title: "Season Twelve", imgsrc:"/assets/seasons/season12.jpg", photo:"/assets/titlecards/s12.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:13,title: "Season Thirteen", imgsrc:"/assets/seasons/season13.jpg", photo:"/assets/titlecards/s13.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:14,title: "Season Fourteen", imgsrc:"/assets/seasons/season14.jpg", photo:"/assets/titlecards/s14.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]},
    {num:15,title: "Season Fifteen", imgsrc:"/assets/seasons/season15.jpg", photo:"/assets/titlecards/s15.gif",description:"", majorUpdates: [{id:"", text:""}], characterIntros: [{id:"", text:""}], epNumbers: "", yearAired: "", totalMonsters:"", bodyCount: "" , epInfo: [{id:"", num:"", photo:"", description:""}], majorDeaths:[{id:"", text:""}]}
]