//{title:"", artist:""},
export const themeSong = {title:"Carry On Wayward Son", artist:"Kansas"};
export const songsSeason1 = [
    {title:"Highway to Hell", artist:"AC/DC"},
    {title:"Back in Black", artist:"AC/DC"},
    {title:"Gasoline", artist:"Torch Ginger"},
    {title:"Whatcha Gonna Do", artist:"Classic"},
    {title:"Speaking in Tongues", artist:"Eagles of Death Metal"},
    {title:"Ramblin' Man", artist:"Allman Brothers Band"},
    {title:"A Gift to the World", artist:"Loveless"},
    {title:"My Cheatin' Ways", artist:"Kid Gloves Music"},
    {title:"Hot Blooded", artist:"Foreigner"},
    {title:"Down South Jukin", artist:"Lynyrd Skynyrd"},
    {title:"Fly By Night", artist:"Rush"},
    {title:"Out of My Hands", artist:"Dave Matthews Band"},
    {title:"Round and Round", artist:"Ratt"},
    {title:"What a Way to Go", artist:"Black Toast Music"},
    {title:"Too Daze Gone", artist:"Billy Squier"},
    {title:"Movin' On", artist:"Bad Company"},
    {title:"Paranoid", artist:"Black Sabbath"},
    {title:"Working Man", artist:"Rush"},
    {title:"Road Rage", artist:"Nichion Sounds Library"},
    {title:"Some Kind of Monster", artist:"Metallica"},
    {title:"Sugar, We're Going Down", artist:"Fall Out Boy"},
    {title:"Rock of Ages", artist:"Def Leppard"},
    {title:"Laugh, I Nearly Died", artist:"The Rolling Stones"},
    {title:"This House is a Hotel", artist:"The Wind and the Wave"},
    {title:"In-A-Gadda-Da-Vida", artist:"Iron Butterfly"},
    {title:"Poison Whiskey", artist:"Lynyrd Skynyrd"},
    {title:"Hey Man, Nice Shot", artist:"Filter"},
    {title:"All Right Now", artist:"Free"},
    {title:"Higher Mathematics", artist:"Split Habit"},
    {title:"Bang your Head (Metal Health)", artist:"Quiet Riot"},
    {title:"Noise", artist:"Low Five"},
    {title:"At Rest", artist:"APM"},
    {title:"Royal Bethlehem", artist:"Leslie Pearson"},
    {title:"U Do 2 Me", artist:"Paul Richard"},
    {title:"Peace of Mind", artist:"Boston"},
    {title:"Dancing On a Wire", artist:"Keygrip"},
    {title:"Operated On", artist:"Union of Knives"},
    {title:"Rock of Ages", artist:"Def Leppard"},
    {title:"Medusa", artist:"Bob Reynolds"},
    {title:"No One Like You", artist:"The Scorpions"},
    {title:"I Got More Bills Than I Got Pay", artist:"Sonny Ellis"},
    {title:"Poke In Tha Butt", artist:"Extreme Music"},
    {title:"Hey You", artist:"Bachman Turner Overdrive"},
    {title:"Lodi", artist:"Creedence Clearwater Revival"},
    {title:"Bad Company", artist:"Bad Company"},
    {title:"Puppet", artist:"Colepitz"},
    {title:"Don't Fear the Reaper", artist:"Blue Oyster Cult"},
    {title:"Death in the Valley", artist:"Death Riders"},
    {title:"Walk Away", artist:"The James Gang"},
    {title:"She Brings Me Love", artist:"Bad Company"},
    {title:"Can't Find My Way Home", artist:"Blind Faith"},
    {title:"Paradise", artist:"Sharif"},
    {title:"Line of Love", artist:"The Minors"},
    {title:"2+2=?", artist:"Bob Seger"},
    {title:"Lucifer", artist:"Bob Seger"},
    {title:"Money & Dealers", artist:"Flickerstick"},
    {title:"Rocky Mountain Way", artist:"Joe Walsh"},
    {title:"Sweet and Low Down", artist:"George Gershwin"},
    {title:"You Got Your Hooks in Me", artist:"Little Charlie and the Nightcats"},
    {title:"Pictures of Me", artist:"The Vue"},
    {title:"The New World", artist:"X"},
    {title:"Jaded Little Love Song", artist:"Rob Meany and Terramara"},
    {title:"Fire of Unknown Origin", artist:"Blue Oyster Cult"},
    {title:"Burnin' For You", artist:"Blue Oyster Cult"},
    {title:"Slow Death", artist:"Extreme Music"},
    {title:"Anthem", artist:"Extreme Music"},
    {title:"Point of No Return", artist:"Rex Horbart and the Misery Boys"},
    {title:"Fast Train Down", artist:"The Waco Brothers"},
    {title:"Vicki and Jacky", artist:"Robert Roth"},
    {title:"Rock Bottom", artist:"UFO"},
    {title:"Road to Nowhere", artist:"Ozzy Osborne"},
    {title:"So Electric", artist:"Boulevard"},
    {title:"Another Day of Regret", artist:"Molly"},
    {title:"Night Time", artist:"Steve Carlson"},
    {title:"Bad Time (To Be In Love)", artist:"Grand Funk Railroad"},
    {title:"Romantic Piece, No. 1", artist:"Extreme"},
    {title:"One More Once", artist:"Black Toast Music"},
    {title:"The House Is Rockin'", artist:"Stevie Ray Vaughan"},
    {title:"Strange Face of Love", artist:"Tito & Tarantula"},
    {title:"Searching for the Truth", artist:"Brian Keith Nutter"},
    {title:"Trailer Trash", artist:"Master Source"},
    {title:"Carry On Wayward Son", artist:"Kansas"},
    {title:"Calling", artist:"Soberskin"},
    {title:"Bad Moon Rising", artist:"Creedence Clearwater Revival"},
    {title:"Fight the Good Fight", artist:"Triumph"},
    {title:"Turn To Stone", artist:"Joe Walsh"},
];
